/**
 * 🔒 LOCKED MODEL: ChatGPT 4o Image
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "4o-image-api",
  recordId: "4b68811b-28be-45cb-bcae-9db721ba4547",
  modelName: "ChatGPT 4o Image",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 3,
  estimatedTimeSeconds: 120,
  costMultipliers: { nVariants: { "1": 1, "2": 1.16666, "4": 1.3333 } },
  apiEndpoint: "/api/v1/gpt4o-image/generate",
  payloadStructure: "flat",
  maxImages: 5,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/openai.png",
  modelFamily: "OpenAI",
  variantName: "ChatGPT 4o Image",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/ChatGPT_4o_Image.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  properties: {
    filesUrl: {
      type: "array",
      description: "URLs of images to edit",
      renderer: "image",
      items: { type: "string", format: "uri" },
    },
    nVariants: {
      type: "integer",
      title: "Number of Outputs",
      default: 1,
      enum: [1, 2, 4],
    },
    prompt: {
      type: "string",
      description: "Editing instruction",
      renderer: "prompt",
    },
    size: {
      type: "string",
      default: "1:1",
      enum: ["1:1", "2:3", "3:2"],
    },
  },
  required: ["size", "prompt", "filesUrl"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.size) return { valid: false, error: "Size is required" };
  if (!inputs.prompt || inputs.prompt.length < 3)
    return { valid: false, error: "Prompt must be at least 3 characters" };
  if (!inputs.filesUrl || !Array.isArray(inputs.filesUrl) || inputs.filesUrl.length === 0) {
    return { valid: false, error: "At least one image URL is required" };
  }
  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    size: inputs.size,
    filesUrl: inputs.filesUrl,
    nVariants: inputs.nVariants || 1,
  };
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  let cost = MODEL_CONFIG.baseCreditCost;
  const nVariants = inputs.nVariants || 1;
  const multiplier = MODEL_CONFIG.costMultipliers.nVariants[String(nVariants) as keyof typeof MODEL_CONFIG.costMultipliers.nVariants] || 1;
  cost *= multiplier;
  return Math.round(cost * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };
  if (uploadedImages.length > 0) inputs.filesUrl = await uploadImagesToStorage(userId);
  const validation = validate(inputs);
  if (!validation.valid) throw new Error(validation.error);
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: modelParameters,
    })
    .select()
    .single();
  if (error || !gen) throw new Error(`Failed: ${error?.message}`);

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke('generate-content', {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs)
    }
  });

  if (funcError) {
    await supabase.from('generations').update({ status: GENERATION_STATUS.FAILED }).eq('id', gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
