/**
 * 🔒 LOCKED MODEL: ChatGPT 4o Image
 * 
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "4o-image-api",
  recordId: "4b68811b-28be-45cb-bcae-9db721ba4547",
  modelName: "ChatGPT 4o Image",
  provider: "kie_ai",
  contentType: "image",
  baseCreditCost: 3,
  estimatedTimeSeconds: 120,
  costMultipliers: { nVariants: { "1": 1, "2": 1.16666, "4": 1.3333 } },
  apiEndpoint: "/api/v1/gpt4o-image/generate",
  payloadStructure: "flat",
  maxImages: 5,
  defaultOutputs: 1,
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  properties: {
    filesUrl: {
      type: "array",
      description: "URLs of images to edit",
      items: { type: "string", format: "uri" }
    },
    nVariants: {
      type: "integer",
      title: "Number of Outputs",
      default: 1,
      enum: [1, 2, 4]
    },
    prompt: {
      type: "string",
      description: "Editing instruction"
    },
    size: {
      type: "string",
      default: "1:1",
      enum: ["1:1", "2:3", "3:2"]
    }
  },
  required: ["size", "prompt", "filesUrl"]
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.size) return { valid: false, error: "Size is required" };
  if (!inputs.prompt || inputs.prompt.length < 3) return { valid: false, error: "Prompt must be at least 3 characters" };
  if (!inputs.filesUrl || !Array.isArray(inputs.filesUrl) || inputs.filesUrl.length === 0) {
    return { valid: false, error: "At least one image URL is required" };
  }
  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    size: inputs.size,
    filesUrl: inputs.filesUrl,
    nVariants: inputs.nVariants || 1
  };
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  let cost = MODEL_CONFIG.baseCreditCost;
  const nVariants = inputs.nVariants || 1;
  const multiplier = MODEL_CONFIG.costMultipliers.nVariants[String(nVariants)] || 1;
  cost *= multiplier;
  return Math.round(cost * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };
  if (uploadedImages.length > 0) inputs.filesUrl = await uploadImagesToStorage(userId);
  const validation = validate(inputs); if (!validation.valid) throw new Error(validation.error);
  const { data: gen, error } = await supabase.from("generations").insert({ user_id: userId, model_id: MODEL_CONFIG.modelId, model_record_id: MODEL_CONFIG.recordId, type: MODEL_CONFIG.contentType, prompt, tokens_used: calculateCost(inputs), status: "pending", settings: modelParameters }).select().single();
  if (error || !gen) throw new Error(`Failed: ${error?.message}`);
  const { data: keyData } = await supabase.functions.invoke('get-api-key', { body: { provider: MODEL_CONFIG.provider, modelId: MODEL_CONFIG.modelId, recordId: MODEL_CONFIG.recordId } });
  if (!keyData?.apiKey) throw new Error('Failed to retrieve API key');
  const res = await fetch(`https://api.kie.ai${MODEL_CONFIG.apiEndpoint}`, { method: "POST", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${keyData.apiKey}` }, body: JSON.stringify(preparePayload(inputs)) });
  if (!res.ok) throw new Error(`API failed: ${res.statusText}`);
  const result = await res.json();
  await supabase.from("generations").update({ provider_task_id: result.taskId || result.id, provider_request: preparePayload(inputs), provider_response: result }).eq("id", gen.id);
  startPolling(gen.id);
  return gen.id;
}
