/**
 * 🔒 LOCKED MODEL: FLUX.1 Kontext Pro
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "flux-kontext-pro",
  recordId: "d0ef1f83-a613-47d4-82f8-10e41da3e2a0",
  modelName: "FLUX.1 Kontext Pro",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 2.5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/flux.png",
  modelFamily: "FLUX",
  variantName: "Flux Kontext Pro",
  displayOrderInFamily: 3,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/FLUX_1_Kontext_Pro.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "inputImage",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "Text prompt describing the desired image or edit. Only English is supported.",
      renderer: "prompt",
    },
    inputImage: {
      type: "string",
      format: "uri",
      title: "Input Image",
      description: "URL of the input image for editing mode. Required when editing an existing image.",
      renderer: "image",
    },
    aspectRatio: {
      type: "string",
      title: "Aspect Ratio",
      description: "Output image aspect ratio",
      default: "16:9",
      enum: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    },
    outputFormat: {
      type: "string",
      title: "Output Format",
      description: "Output image format",
      default: "jpeg",
      enum: ["jpeg", "png"],
    },

    // Optional parameters (hidden from UI)
    enableTranslation: {
      type: "boolean",
      title: "Enable Translation",
      description: "Auto-translate non-English prompts to English",
      default: true,
      showToUser: false,
    },
    promptUpsampling: {
      type: "boolean",
      title: "Prompt Upsampling",
      description: "Performs upsampling on the prompt. May increase processing time.",
      default: false,
      showToUser: false,
    },
    safetyTolerance: {
      type: "integer",
      title: "Safety Tolerance",
      description: "Moderation level (0=strict to 6=permissive for generation, 0-2 for editing)",
      default: 2,
      enum: [0, 1, 2, 3, 4, 5, 6],
      showToUser: false,
    },
    watermark: {
      type: "string",
      title: "Watermark",
      description: "Watermark identifier to add to the generated image",
      showToUser: false,
    },
    uploadCn: {
      type: "boolean",
      title: "Upload via China Servers",
      description: "Use China servers for image upload (for users in China)",
      default: false,
      showToUser: false,
    },
  },
  required: ["prompt"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (inputs.aspectRatio !== undefined && !["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"].includes(inputs.aspectRatio)) {
    return { valid: false, error: "Invalid aspect ratio" };
  }

  if (inputs.outputFormat !== undefined && !["jpeg", "png"].includes(inputs.outputFormat)) {
    return { valid: false, error: "Output format must be jpeg or png" };
  }

  if (inputs.safetyTolerance !== undefined && ![0, 1, 2, 3, 4, 5, 6].includes(inputs.safetyTolerance)) {
    return { valid: false, error: "Safety tolerance must be between 0 and 6" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  const payload: Record<string, any> = {
    prompt: inputs.prompt,
    model: MODEL_CONFIG.modelId,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: inputs.enableTranslation ?? true,
  };

  // Add input image if provided (editing mode)
  if (inputs.inputImage) {
    payload.inputImage = inputs.inputImage;
  }

  // Add optional parameters only if provided
  if (inputs.promptUpsampling !== undefined) {
    payload.promptUpsampling = inputs.promptUpsampling;
  }

  if (inputs.safetyTolerance !== undefined) {
    payload.safetyTolerance = inputs.safetyTolerance;
  }

  if (inputs.watermark) {
    payload.watermark = inputs.watermark;
  }

  if (inputs.uploadCn !== undefined) {
    payload.uploadCn = inputs.uploadCn;
  }

  return payload;
}

// COST CALCULATION
export function calculateCost(_inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };

  // Upload image and get URL if provided
  if (uploadedImages.length > 0) {
    inputs.inputImage = (await uploadImagesToStorage(userId))[0];
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
