/**
 * ISOLATED MODEL FILE: FLUX.1 Kontext Max (Image Editing)
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is locked and managed by the admin interface
 * 
 * Model ID: flux-kontext-max
 * Record ID: ab0ae096-f0ef-4197-b186-f38d69e72dd3
 * Provider: kie_ai
 * Content Type: image
 */


/**
 * Model configuration constants
 */
export const MODEL_CONFIG = {
  modelId: "flux-kontext-max",
  recordId: "ab0ae096-f0ef-4197-b186-f38d69e72dd3",
  modelName: "FLUX.1 Kontext Max",
  provider: "kie_ai",
  contentType: "image",
  baseCreditCost: 5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,
} as const;

/**
 * Frozen input schema - defines what UI shows
 */
export const SCHEMA = {
  "imageInputField": "inputImage",
  "properties": {
    "aspectRatio": {
      "default": "16:9",
      "enum": ["1:1", "3:4", "4:3", "9:16", "16:9", "21:9"],
      "type": "string"
    },
    "enableTranslation": {
      "default": true,
      "enum": [true, false],
      "showToUser": false,
      "type": "boolean"
    },
    "inputImage": {
      "renderer": "image",
      "title": "Upload your image",
      "type": "string"
    },
    "outputFormat": {
      "default": "jpeg",
      "enum": ["jpeg", "png"],
      "type": "string"
    },
    "prompt": {
      "renderer": "prompt",
      "type": "string"
    }
  },
  "required": ["prompt", "inputImage"],
  "type": "object"
} as const;

/**
 * Validate user inputs against schema
 */
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  const required = SCHEMA.required || [];
  
  for (const field of required) {
    if (!inputs[field]) {
      return { valid: false, error: `Missing required field: ${field}` };
    }
  }
  
  return { valid: true };
}

/**
 * Prepare API payload from user inputs
 */
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    inputImage: inputs.inputImage,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: true,
  };
}

/**
 * Calculate credit cost for this generation
 */
export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

