/**
 * ISOLATED MODEL FILE: FLUX.1 Kontext Pro (Image Editing)
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is locked and managed by the admin interface
 * 
 * Model ID: flux-kontext-pro
 * Record ID: d0ef1f83-a613-47d4-82f8-10e41da3e2a0
 * Provider: kie_ai
 * Content Type: image
 */


export const MODEL_CONFIG = {
  modelId: "flux-kontext-pro",
  recordId: "d0ef1f83-a613-47d4-82f8-10e41da3e2a0",
  modelName: "FLUX.1 Kontext Pro",
  provider: "kie_ai",
  contentType: "image",
  baseCreditCost: 2.5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,
} as const;

export const SCHEMA = {
  "imageInputField": "inputImage",
  "properties": {
    "aspectRatio": {
      "default": "16:9",
      "enum": ["1:1", "3:4", "4:3", "9:16", "16:9", "21:9"],
      "type": "string"
    },
    "enableTranslation": {
      "default": true,
      "enum": [true, false],
      "showToUser": false,
      "type": "boolean"
    },
    "inputImage": {
      "renderer": "image",
      "title": "Upload your image",
      "type": "string"
    },
    "outputFormat": {
      "default": "jpeg",
      "enum": ["jpeg", "png"],
      "type": "string"
    },
    "prompt": {
      "renderer": "prompt",
      "type": "string"
    }
  },
  "required": ["prompt", "inputImage"],
  "type": "object"
} as const;

export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt || !inputs.inputImage) {
    return { valid: false, error: "Missing required fields" };
  }
  return { valid: true };
}

export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    inputImage: inputs.inputImage,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: true,
  };
}

export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

