/**
 * ISOLATED MODEL FILE: FLUX.1 Kontext Max (Image Editing)
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is locked and managed by the admin interface
 * 
 * Model ID: flux-kontext-max
 * Record ID: ab0ae096-f0ef-4197-b186-f38d69e72dd3
 * Provider: kie_ai
 * Content Type: image
 */

import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";

/**
 * Model configuration constants
 */
export const MODEL_CONFIG = {
  modelId: "flux-kontext-max",
  recordId: "ab0ae096-f0ef-4197-b186-f38d69e72dd3",
  modelName: "FLUX.1 Kontext Max",
  provider: "kie_ai",
  contentType: "image",
  baseCreditCost: 5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,
} as const;

/**
 * Frozen input schema - defines what UI shows
 */
export const SCHEMA = {
  "imageInputField": "inputImage",
  "properties": {
    "aspectRatio": {
      "default": "16:9",
      "enum": ["1:1", "3:4", "4:3", "9:16", "16:9", "21:9"],
      "type": "string"
    },
    "enableTranslation": {
      "default": true,
      "enum": [true, false],
      "showToUser": false,
      "type": "boolean"
    },
    "inputImage": {
      "renderer": "image",
      "title": "Upload your image",
      "type": "string"
    },
    "outputFormat": {
      "default": "jpeg",
      "enum": ["jpeg", "png"],
      "type": "string"
    },
    "prompt": {
      "renderer": "prompt",
      "type": "string"
    }
  },
  "required": ["prompt", "inputImage"],
  "type": "object"
} as const;

/**
 * Validate user inputs against schema
 */
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  const required = SCHEMA.required || [];
  
  for (const field of required) {
    if (!inputs[field]) {
      return { valid: false, error: `Missing required field: ${field}` };
    }
  }
  
  return { valid: true };
}

/**
 * Prepare API payload from user inputs
 */
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    inputImage: inputs.inputImage,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: true,
  };
}

/**
 * Calculate credit cost for this generation
 */
export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

/**
 * Execute generation - Direct API call
 */
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { model, prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, generate, startPolling, navigate } = params;
  
  // Prepare inputs with uploaded images
  const inputs: Record<string, any> = { prompt, ...modelParameters };
  
  // Upload images if provided
  if (uploadedImages.length > 0) {
    const imageUrls = await uploadImagesToStorage(userId);
    inputs.inputImage = imageUrls[0];
  }
  
  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }
  
  // Calculate cost
  const cost = calculateCost(inputs);
  
  // Create generation record
  const { data: generation, error: genError } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: MODEL_CONFIG.contentType,
      prompt: prompt,
      tokens_used: cost,
      status: "pending",
      settings: modelParameters,
    })
    .select()
    .single();
  
  if (genError || !generation) {
    throw new Error(`Failed to create generation: ${genError?.message}`);
  }
  
  // Prepare payload
  const payload = preparePayload(inputs);
  
  // Call kie_ai API
  const apiKey = await getKieApiKey();
  const response = await fetch(`https://api.kie.ai${MODEL_CONFIG.apiEndpoint}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
    },
    body: JSON.stringify(payload),
  });
  
  if (!response.ok) {
    throw new Error(`API call failed: ${response.statusText}`);
  }
  
  const result = await response.json();
  
  // Update generation with provider details
  await supabase
    .from("generations")
    .update({
      provider_task_id: result.taskId || result.id,
      provider_request: payload,
      provider_response: result,
    })
    .eq("id", generation.id);
  
  // Start polling
  startPolling(generation.id);
  
  return generation.id;
}

/**
 * Helper to get kie_ai API key from secrets
 */
async function getKieApiKey(): Promise<string> {
  // TODO: Implement proper secrets management
  // For now, this will need to be configured via environment or edge function
  throw new Error("KIE_API_KEY needs to be configured in secrets");
}
