/**
 * ISOLATED MODEL FILE: FLUX.1 Kontext Max (Image Editing)
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is locked and managed by the admin interface
 *
 * Model ID: flux-kontext-max
 * Record ID: ab0ae096-f0ef-4197-b186-f38d69e72dd3
 * Provider: kie_ai
 * Content Type: image
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";

/**
 * Model configuration constants
 */
export const MODEL_CONFIG = {
  modelId: "flux-kontext-max",
  recordId: "ab0ae096-f0ef-4197-b186-f38d69e72dd3",
  modelName: "FLUX.1 Kontext Max",
  provider: "kie_ai",
  contentType: "image_editing",
  baseCreditCost: 5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/public/logos/flux.png",
  modelFamily: "FLUX",
  variantName: "1 Kontext Max",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/FLUX_1_Kontext_Max.ts",
} as const;

/**
 * Frozen input schema - defines what UI shows
 */
export const SCHEMA = {
  imageInputField: "inputImage",
  properties: {
    aspectRatio: {
      default: "16:9",
      enum: ["1:1", "3:4", "4:3", "9:16", "16:9", "21:9"],
      type: "string",
    },
    enableTranslation: {
      default: true,
      enum: [true, false],
      showToUser: false,
      type: "boolean",
    },
    inputImage: {
      renderer: "image",
      title: "Upload your image",
      type: "string",
    },
    outputFormat: {
      default: "jpeg",
      enum: ["jpeg", "png"],
      type: "string",
    },
    prompt: {
      renderer: "prompt",
      type: "string",
    },
  },
  required: ["prompt", "inputImage"],
  type: "object",
} as const;

/**
 * Validate user inputs against schema
 */
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  const required = SCHEMA.required || [];

  for (const field of required) {
    if (!inputs[field]) {
      return { valid: false, error: `Missing required field: ${field}` };
    }
  }

  return { valid: true };
}

/**
 * Prepare API payload from user inputs
 */
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    inputImage: inputs.inputImage,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: true,
  };
}

/**
 * Calculate credit cost for this generation
 */
export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

/**
 * Execute generation
 */
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };
  if (uploadedImages.length > 0) inputs.inputImage = (await uploadImagesToStorage(userId))[0];
  const validation = validate(inputs);
  if (!validation.valid) throw new Error(validation.error);
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: "pending",
      settings: modelParameters,
    })
    .select()
    .single();
  if (error || !gen) throw new Error(`Failed: ${error?.message}`);
  const { data: keyData } = await supabase.functions.invoke("get-api-key", {
    body: { provider: MODEL_CONFIG.provider, modelId: MODEL_CONFIG.modelId, recordId: MODEL_CONFIG.recordId },
  });
  if (!keyData?.apiKey) throw new Error("Failed to retrieve API key");
  const res = await fetch(`https://api.kie.ai${MODEL_CONFIG.apiEndpoint}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${keyData.apiKey}` },
    body: JSON.stringify(preparePayload(inputs)),
  });
  if (!res.ok) throw new Error(`API failed: ${res.statusText}`);
  const result = await res.json();
  await supabase
    .from("generations")
    .update({
      provider_task_id: result.taskId || result.id,
      provider_request: preparePayload(inputs),
      provider_response: result,
    })
    .eq("id", gen.id);
  startPolling(gen.id);
  return gen.id;
}
