/**
 * 🔒 LOCKED MODEL: FLUX 2 Flex Image-to-Image
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "flux-2/flex-image-to-image",
  recordId: "e1f2a3b4-5c6d-7e8f-9a0b-1c2d3e4f5a6b",
  modelName: "FLUX 2 Flex Image-to-Image",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 3,
  estimatedTimeSeconds: 40,
  costMultipliers: {
    resolution: { "1K": 1, "2K": 1.5 },
  },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 8,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/flux.png",
  modelFamily: "FLUX",
  variantName: "2 Flex Image-to-Image",
  displayOrderInFamily: 4,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/FLUX_2_Flex_Image_to_Image.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "input_urls",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "A text description of the image you want to generate. Must be between 3 and 5000 characters.",
      minLength: 3,
      maxLength: 5000,
      renderer: "prompt",
    },
    input_urls: {
      type: "array",
      title: "Input Images",
      description: "Input reference images (1-8 images). Formats: JPEG, PNG, WebP. Max size: 10MB each.",
      renderer: "image",
      items: { type: "string", format: "uri" },
      minItems: 1,
      maxItems: 8,
    },
    aspect_ratio: {
      type: "string",
      title: "Aspect Ratio",
      description: "Aspect ratio for the generated image. Select 'auto' to match the first input image ratio.",
      default: "1:1",
      enum: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "auto"],
      enumLabels: {
        "1:1": "1:1 (Square)",
        "4:3": "4:3 (Landscape)",
        "3:4": "3:4 (Portrait)",
        "16:9": "16:9 (Widescreen)",
        "9:16": "9:16 (Vertical)",
        "3:2": "3:2 (Classic)",
        "2:3": "2:3 (Classic Portrait)",
        "auto": "Auto (Based on first input image)",
      },
    },
    resolution: {
      type: "string",
      title: "Resolution",
      description: "Output image resolution",
      default: "1K",
      enum: ["1K", "2K"],
    },
  },
  required: ["prompt", "input_urls", "aspect_ratio", "resolution"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (inputs.prompt.length < 3) {
    return { valid: false, error: "Prompt must be at least 3 characters" };
  }

  if (inputs.prompt.length > 5000) {
    return { valid: false, error: "Prompt must be 5000 characters or less" };
  }

  if (!inputs.input_urls || !Array.isArray(inputs.input_urls) || inputs.input_urls.length === 0) {
    return { valid: false, error: "At least one input image URL is required" };
  }

  if (inputs.input_urls.length > 8) {
    return { valid: false, error: "Maximum 8 input images allowed" };
  }

  if (!inputs.aspect_ratio) {
    return { valid: false, error: "Aspect ratio is required" };
  }

  if (!["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "auto"].includes(inputs.aspect_ratio)) {
    return { valid: false, error: "Invalid aspect_ratio value" };
  }

  if (!inputs.resolution) {
    return { valid: false, error: "Resolution is required" };
  }

  if (!["1K", "2K"].includes(inputs.resolution)) {
    return { valid: false, error: "Resolution must be 1K or 2K" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    model: MODEL_CONFIG.modelId,
    input: {
      prompt: inputs.prompt,
      input_urls: inputs.input_urls,
      aspect_ratio: inputs.aspect_ratio || "1:1",
      resolution: inputs.resolution || "1K",
    },
  };
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;

  // Resolution multiplier
  const resolutionKey = (inputs.resolution || "1K") as keyof typeof MODEL_CONFIG.costMultipliers.resolution;
  const resolutionMult = MODEL_CONFIG.costMultipliers.resolution[resolutionKey] || 1;

  return Math.round(base * resolutionMult * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { prompt, ...modelParameters };

  // Upload images and get URLs if provided
  if (uploadedImages.length > 0) {
    inputs.input_urls = await uploadImagesToStorage(userId);
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
