/**
 * ISOLATED MODEL FILE: FLUX.1 Kontext Pro (Image Editing)
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is locked and managed by the admin interface
 * 
 * Model ID: flux-kontext-pro
 * Record ID: d0ef1f83-a613-47d4-82f8-10e41da3e2a0
 * Provider: kie_ai
 * Content Type: image
 */

import { getGenerationType } from '@/lib/models/registry';
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";

export const MODEL_CONFIG = {
  modelId: "flux-kontext-pro",
  recordId: "d0ef1f83-a613-47d4-82f8-10e41da3e2a0",
  modelName: "FLUX.1 Kontext Pro",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 2.5,
  estimatedTimeSeconds: 50,
  costMultipliers: {},
  apiEndpoint: "/api/v1/flux/kontext/generate",
  payloadStructure: "flat",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/flux.png",
  modelFamily: "FLUX",
  variantName: "1 Kontext Pro",
  displayOrderInFamily: 3,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/FLUX_1_Kontext_Pro.ts"
} as const;

export const SCHEMA = {
  "imageInputField": "inputImage",
  "properties": {
    "aspectRatio": {
      "default": "16:9",
      "enum": ["1:1", "3:4", "4:3", "9:16", "16:9", "21:9"],
      "type": "string"
    },
    "enableTranslation": {
      "default": true,
      "enum": [true, false],
      "showToUser": false,
      "type": "boolean"
    },
    "inputImage": {
      "renderer": "image",
      "title": "Upload your image",
      "type": "string"
    },
    "outputFormat": {
      "default": "jpeg",
      "enum": ["jpeg", "png"],
      "type": "string"
    },
    "prompt": {
      "renderer": "prompt",
      "type": "string"
    }
  },
  "required": ["prompt", "inputImage"],
  "type": "object"
} as const;

export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt || !inputs.inputImage) {
    return { valid: false, error: "Missing required fields" };
  }
  return { valid: true };
}

export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    inputImage: inputs.inputImage,
    aspectRatio: inputs.aspectRatio || "16:9",
    outputFormat: inputs.outputFormat || "jpeg",
    enableTranslation: true,
  };
}

export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };
  if (uploadedImages.length > 0) inputs.inputImage = (await uploadImagesToStorage(userId))[0];
  const validation = validate(inputs); if (!validation.valid) throw new Error(validation.error);
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase.from("generations").insert({ user_id: userId, model_id: MODEL_CONFIG.modelId, model_record_id: MODEL_CONFIG.recordId, type: getGenerationType(MODEL_CONFIG.contentType), prompt, tokens_used: cost, status: GENERATION_STATUS.PENDING, settings: modelParameters }).select().single();
  if (error || !gen) throw new Error(`Failed: ${error?.message}`);

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke('generate-content', {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs)
    }
  });

  if (funcError) {
    await supabase.from('generations').update({ status: GENERATION_STATUS.FAILED }).eq('id', gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}

