/**
 * 🔒 LOCKED MODEL: Ideogram Character
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "ideogram/character",
  recordId: "4a421ed9-ed0c-40bf-b06d-892871506124",
  modelName: "Ideogram Character",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 6,
  estimatedTimeSeconds: 25,
  costMultipliers: {
    num_images: { "1": 1, "2": 2, "3": 3, "4": 4 },
    rendering_speed: { TURBO: 1, BALANCED: 1.5, QUALITY: 2 },
  },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/ideogram.png",
  modelFamily: "Ideogram",
  variantName: "Character",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Ideogram_Character.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "reference_image_urls",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "The prompt to generate the character image with",
      maxLength: 5000,
      renderer: "prompt",
    },
    reference_image_urls: {
      type: "array",
      title: "Character Reference Images",
      description:
        "A set of images to use as character references. Currently only 1 image is supported. Max total size 10MB. Formats: JPEG, PNG, WebP",
      renderer: "image",
      items: { type: "string", format: "uri" },
      maxItems: 5,
    },
    image_size: {
      type: "string",
      title: "Output Size",
      description: "The resolution of the generated image",
      default: "square_hd",
      enum: ["square", "square_hd", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"],
    },
    rendering_speed: {
      type: "string",
      title: "Rendering Speed",
      description: "The rendering speed to use",
      default: "BALANCED",
      enum: ["TURBO", "BALANCED", "QUALITY"],
    },
    style: {
      type: "string",
      title: "Style",
      description: "The style type to generate with",
      default: "AUTO",
      isAdvanced: true,
      enum: ["AUTO", "REALISTIC", "FICTION"],
    },
    num_images: {
      type: "string",
      title: "Number of Images",
      description: "Number of images to generate",
      default: "1",
      enum: ["1", "2", "3", "4"],
    },

    // Optional parameters
    negative_prompt: {
      type: "string",
      title: "Negative Prompt",
      description: "Description of what to exclude from an image",
      maxLength: 5000,
      isAdvanced: true,
    },
    expand_prompt: {
      type: "boolean",
      title: "Expand Prompt (MagicPrompt)",
      description: "Determine if MagicPrompt should be used in generating the request",
      default: true,
      showToUser: false,
    },

    // Hidden parameters
    seed: {
      type: "integer",
      title: "Seed",
      description: "Seed for the random number generator",
      isAdvanced: true,
    },
  },
  required: ["prompt", "reference_image_urls"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (
    !inputs.reference_image_urls ||
    !Array.isArray(inputs.reference_image_urls) ||
    inputs.reference_image_urls.length === 0
  ) {
    return { valid: false, error: "At least one reference image URL is required" };
  }

  if (
    inputs.image_size !== undefined &&
    !["square", "square_hd", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"].includes(
      inputs.image_size,
    )
  ) {
    return { valid: false, error: "Invalid image_size value" };
  }

  if (inputs.rendering_speed !== undefined && !["TURBO", "BALANCED", "QUALITY"].includes(inputs.rendering_speed)) {
    return { valid: false, error: "rendering_speed must be TURBO, BALANCED, or QUALITY" };
  }

  if (inputs.style !== undefined && !["AUTO", "REALISTIC", "FICTION"].includes(inputs.style)) {
    return { valid: false, error: "style must be AUTO, REALISTIC, or FICTION" };
  }

  if (inputs.num_images !== undefined && !["1", "2", "3", "4"].includes(inputs.num_images)) {
    return { valid: false, error: "num_images must be 1, 2, 3, or 4" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  const payload: Record<string, any> = {
    model: MODEL_CONFIG.modelId,
    input: {
      prompt: inputs.prompt,
      reference_image_urls: inputs.reference_image_urls,
      image_size: inputs.image_size || "square_hd",
      rendering_speed: inputs.rendering_speed || "BALANCED",
      style: inputs.style || "AUTO",
      num_images: inputs.num_images || "1",
      expand_prompt: inputs.expand_prompt !== false,
    },
  };

  // Add optional parameters only if provided
  if (inputs.negative_prompt) {
    payload.input.negative_prompt = inputs.negative_prompt;
  }

  if (inputs.seed !== undefined && inputs.seed !== null) {
    payload.input.seed = inputs.seed;
  }

  return payload;
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;

  // Speed multiplier
  const speedKey = (inputs.rendering_speed || "BALANCED") as keyof typeof MODEL_CONFIG.costMultipliers.rendering_speed;
  const speedMult = MODEL_CONFIG.costMultipliers.rendering_speed[speedKey] || 1;

  // Number of images multiplier
  const numImagesKey = String(
    parseInt(inputs.num_images || "1"),
  ) as keyof typeof MODEL_CONFIG.costMultipliers.num_images;
  const numMult = MODEL_CONFIG.costMultipliers.num_images[numImagesKey] || 1;

  return Math.round(base * speedMult * numMult * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { prompt, ...modelParameters };

  // Upload images and get URLs if provided
  if (uploadedImages.length > 0) {
    inputs.reference_image_urls = await uploadImagesToStorage(userId);
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed to create generation: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
