/**
 * 🔒 LOCKED MODEL: Ideogram V3 Reframe
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import { extractEdgeFunctionError } from "@/lib/utils/edge-function-error";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "ideogram/v3-reframe",
  recordId: "2c4802d0-f805-4c31-bab1-a07675e003eb",
  modelName: "Ideogram V3 Reframe",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 1.75,
  estimatedTimeSeconds: 60,
  costMultipliers: {
    num_images: { "1": 1, "2": 2, "3": 3, "4": 4 },
    rendering_speed: { TURBO: 1, BALANCED: 2, QUALITY: 3 },
  },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/ideogram.png",
  modelFamily: "Ideogram",
  variantName: "V3 Reframe",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Ideogram_V3_Reframe.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "image_url",
  properties: {
    // Required parameters (shown in UI)
    image_url: {
      type: "string",
      format: "uri",
      title: "Image to Reframe",
      description: "The image URL to reframe",
      renderer: "image",
    },
    image_size: {
      type: "string",
      title: "Output Size",
      description: "The resolution for the reframed output image",
      default: "square",
      enum: ["square", "square_hd", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"],
    },
    rendering_speed: {
      type: "string",
      title: "Rendering Speed",
      description: "The rendering speed to use",
      default: "TURBO",
      enum: ["TURBO", "BALANCED", "QUALITY"],
    },
    style: {
      type: "string",
      title: "Style",
      description: "The style type to generate with",
      default: "AUTO",
      enum: ["AUTO", "GENERAL", "REALISTIC", "DESIGN"],
    },
    num_images: {
      type: "string",
      title: "Number of Images",
      description: "Number of images to generate",
      default: "1",
      enum: ["1", "2", "3", "4"],
    },

    // Optional parameters (hidden from UI)
    seed: {
      type: "number",
      title: "Seed",
      description: "Seed for the random number generator",
      showToUser: false,
    },
  },
  required: ["image_url", "image_size"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.image_url) {
    return { valid: false, error: "Image URL is required" };
  }

  if (!inputs.image_size) {
    return { valid: false, error: "Image size is required" };
  }

  if (
    !["square", "square_hd", "portrait_4_3", "portrait_16_9", "landscape_4_3", "landscape_16_9"].includes(
      inputs.image_size,
    )
  ) {
    return { valid: false, error: "Invalid image_size value" };
  }

  if (inputs.rendering_speed !== undefined && !["TURBO", "BALANCED", "QUALITY"].includes(inputs.rendering_speed)) {
    return { valid: false, error: "rendering_speed must be TURBO, BALANCED, or QUALITY" };
  }

  if (inputs.style !== undefined && !["AUTO", "GENERAL", "REALISTIC", "DESIGN"].includes(inputs.style)) {
    return { valid: false, error: "Invalid style value" };
  }

  if (inputs.num_images !== undefined && !["1", "2", "3", "4"].includes(inputs.num_images)) {
    return { valid: false, error: "num_images must be 1, 2, 3, or 4" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  const payload: Record<string, any> = {
    model: MODEL_CONFIG.modelId,
    input: {
      image_url: inputs.image_url,
      image_size: inputs.image_size || "square",
      rendering_speed: inputs.rendering_speed || "TURBO",
      style: inputs.style || "AUTO",
      num_images: inputs.num_images || "1",
    },
  };

  // Add optional seed if provided
  if (inputs.seed !== undefined && inputs.seed !== null) {
    payload.input.seed = inputs.seed;
  }

  return payload;
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;

  // Speed multiplier
  const speedKey = (inputs.rendering_speed || "TURBO") as keyof typeof MODEL_CONFIG.costMultipliers.rendering_speed;
  const speedMult = MODEL_CONFIG.costMultipliers.rendering_speed[speedKey] || 1;

  // Number of images multiplier
  const numImagesKey = String(
    parseInt(inputs.num_images || "1"),
  ) as keyof typeof MODEL_CONFIG.costMultipliers.num_images;
  const numMult = MODEL_CONFIG.costMultipliers.num_images[numImagesKey] || 1;

  return Math.round(base * speedMult * numMult * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { prompt, ...modelParameters };

  // Upload image and get URL if provided
  if (uploadedImages.length > 0) {
    inputs.image_url = (await uploadImagesToStorage(userId))[0];
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt: prompt || "Reframe image",
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt: prompt || "Reframe image",
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    const errorMessage = await extractEdgeFunctionError(funcError);
    throw new Error(errorMessage);
  }

  startPolling(gen.id);
  return gen.id;
}
