/**
 * 🔒 LOCKED MODEL: Nano Banana Pro (Image Editing)
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image_editing
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "nano-banana-pro",
  recordId: "b4c5d6e7-8f9a-0b1c-2d3e-4f5a6b7c8d9e",
  modelName: "Nano Banana Pro",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 9,
  estimatedTimeSeconds: 35,
  costMultipliers: {
    resolution: { "1K": 1, "2K": 1, "4K": 1.333 },
  },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 8,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/google.png",
  modelFamily: "Google",
  variantName: "Nano Banana Pro",
  displayOrderInFamily: 1,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Nano_Banana_Pro.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "image_input",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "A text description of the image you want to generate",
      maxLength: 10000,
      renderer: "prompt",
    },

    // Required for image editing
    image_input: {
      type: "array",
      title: "Input Images",
      description:
        "Input images to transform or use as reference (supports up to 8 images). Formats: JPEG, PNG, WebP. Max size: 30MB.",
      renderer: "image",
      items: { type: "string", format: "uri" },
      minItems: 1,
      maxItems: 8,
    },
    aspect_ratio: {
      type: "string",
      title: "Aspect Ratio",
      description: "Aspect ratio of the generated image",
      default: "1:1",
      enum: ["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9", "auto"],
    },
    resolution: {
      type: "string",
      title: "Resolution",
      description: "Resolution of the generated image",
      default: "1K",
      enum: ["1K", "2K", "4K"],
    },
    output_format: {
      type: "string",
      title: "Output Format",
      description: "Format of the output image",
      default: "png",
      enum: ["png", "jpg"],
    },
  },
  required: ["prompt", "image_input"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (inputs.prompt.length > 10000) {
    return { valid: false, error: "Prompt must be 10000 characters or less" };
  }

  if (!inputs.image_input || !Array.isArray(inputs.image_input) || inputs.image_input.length === 0) {
    return { valid: false, error: "At least one input image is required for image editing" };
  }

  if (inputs.image_input.length > 8) {
    return { valid: false, error: "Maximum 8 input images allowed" };
  }

  if (
    inputs.aspect_ratio !== undefined &&
    !["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9", "auto"].includes(inputs.aspect_ratio)
  ) {
    return { valid: false, error: "Invalid aspect_ratio value" };
  }

  if (inputs.resolution !== undefined && !["1K", "2K", "4K"].includes(inputs.resolution)) {
    return { valid: false, error: "Resolution must be 1K, 2K, or 4K" };
  }

  if (inputs.output_format !== undefined && !["png", "jpg"].includes(inputs.output_format)) {
    return { valid: false, error: "Output format must be png or jpg" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  const payload: Record<string, any> = {
    model: MODEL_CONFIG.modelId,
    input: {
      prompt: inputs.prompt,
      image_input: inputs.image_input,
    },
  };

  if (inputs.aspect_ratio) {
    payload.input.aspect_ratio = inputs.aspect_ratio;
  }

  if (inputs.resolution) {
    payload.input.resolution = inputs.resolution;
  }

  if (inputs.output_format) {
    payload.input.output_format = inputs.output_format;
  }

  return payload;
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;

  // Resolution multiplier
  const resolutionKey = (inputs.resolution || "1K") as keyof typeof MODEL_CONFIG.costMultipliers.resolution;
  const resolutionMult = MODEL_CONFIG.costMultipliers.resolution[resolutionKey] || 1;

  return Math.round(base * resolutionMult * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { prompt, ...modelParameters };

  // Upload images and get URLs if provided
  if (uploadedImages.length > 0) {
    inputs.image_input = await uploadImagesToStorage(userId);
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
