/**
 * 🔒 LOCKED MODEL: Crisp Image Upscale
 * 
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 */

import { getGenerationType } from '@/lib/models/registry';
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { supabase } from "@/integrations/supabase/client";
import { reserveCredits } from "@/lib/models/creditDeduction";

export const MODEL_CONFIG = {
  modelId: "recraft/crisp-upscale",
  recordId: "00ef3f28-4fab-4244-b93f-0ba48641fcbd",
  modelName: "Crisp Image Upscale",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 0.25,
  estimatedTimeSeconds: 20,
  costMultipliers: {},
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/recraft.png",
  modelFamily: "Kie Ai",
  variantName: "Crisp Image Upscale",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Recraft_Crisp_Upscale.ts"
} as const;

export const SCHEMA = {
  type: "object",
  properties: {
    image: {
      type: "string",
      description: "Image to upscale. Accepted types: image/jpeg, image/png, image/webp; Max size: 10.0MB",
      renderer: "image"
    }
  },
  required: ["image"],
  imageInputField: "image",
  "x-order": ["image"]
};

export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.image) return { valid: false, error: "Image is required" };
  return { valid: true };
}

export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    modelId: MODEL_CONFIG.modelId,
    input: {
      image: inputs.image
    }
  };
}

export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, userId, uploadedImageUrls, startPolling } = params;

  // Map uploaded image URL to the image parameter
  const inputs = {
    ...modelParameters,
    prompt,
    image: uploadedImageUrls[0] || modelParameters.image
  };

  const validation = validate(inputs);
  if (!validation.valid) throw new Error(validation.error);

  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: generation, error: genError } = await supabase
    .from('generations')
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      prompt: prompt || "Upscale image",
      type: getGenerationType(MODEL_CONFIG.contentType),
      status: 'pending',
      tokens_used: cost,
      settings: modelParameters
    })
    .select()
    .single();

  if (genError || !generation) throw new Error(`Failed to create generation: ${genError?.message}`);

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke('generate-content', {
    body: {
      generationId: generation.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt: prompt || "Upscale image",
      custom_parameters: preparePayload(inputs)
    }
  });

  if (funcError) {
    await supabase.from('generations').update({ status: 'failed' }).eq('id', generation.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(generation.id);
  return generation.id;
}
