/**
 * 🔒 LOCKED MODEL: Crisp Image Upscale
 * 
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 */

import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { supabase } from "@/integrations/supabase/client";
import { reserveCredits } from "@/lib/models/creditDeduction";

export const MODEL_CONFIG = {
  modelId: "recraft/crisp-upscale",
  recordId: "00ef3f28-4fab-4244-b93f-0ba48641fcbd",
  modelName: "Crisp Image Upscale",
  provider: "kie_ai",
  contentType: "image",
  baseCreditCost: 0.25,
  estimatedTimeSeconds: 20,
  costMultipliers: {},
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 1,
  defaultOutputs: 1,
} as const;

export const SCHEMA = {
  type: "object",
  properties: {
    image: {
      type: "string",
      description: "Image to upscale. Accepted types: image/jpeg, image/png, image/webp; Max size: 10.0MB",
      renderer: "image"
    }
  },
  required: ["image"],
  imageInputField: "image",
  "x-order": ["image"]
};

export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.image) return { valid: false, error: "Image is required" };
  return { valid: true };
}

export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return { image: inputs.image };
}

export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, userId } = params;
  const validation = validate({ ...modelParameters, prompt });
  if (!validation.valid) throw new Error(validation.error);
  
  const cost = calculateCost({ ...modelParameters, prompt });
  await reserveCredits(userId, cost);
  const { data: generation, error: genError } = await supabase
    .from('generations')
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      prompt: prompt || "Upscale image",
      type: MODEL_CONFIG.contentType,
      status: 'processing',
      tokens_used: cost,
      settings: modelParameters
    })
    .select()
    .single();

  if (genError || !generation) throw new Error(`Failed to create generation: ${genError?.message}`);

  const payload = { task: MODEL_CONFIG.modelId.split('/')[1], input: preparePayload({ ...modelParameters, prompt }) };

  try {
    const response = await fetch(`https://api.klingai.com${MODEL_CONFIG.apiEndpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${await getKieApiKey()}` },
      body: JSON.stringify(payload)
    });

    if (!response.ok) throw new Error(`API call failed: ${response.statusText}`);
    const result = await response.json();
    
    await supabase.from('generations').update({
      provider_task_id: result.taskId,
      provider_request: payload,
      provider_response: result
    }).eq('id', generation.id);

    params.startPolling(generation.id);
    return generation.id;
  } catch (error) {
    await supabase.from('generations').update({ status: 'failed' }).eq('id', generation.id);
    throw error;
  }
}

async function getKieApiKey(): Promise<string> {
  const { data, error } = await supabase.functions.invoke('get-api-key', { body: { provider: 'kie_ai' } });
  if (error || !data?.apiKey) throw new Error('Failed to get API key');
  return data.apiKey;
}
