/**
 * 🔒 LOCKED MODEL: Seedream 4.5
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import { extractEdgeFunctionError } from "@/lib/utils/edge-function-error";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "seedream/4.5-edit",
  recordId: "a3b4c5d6-7e8f-9a0b-1c2d-3e4f5a6b7c8d",
  modelName: "Seedream 4.5",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 3.5,
  estimatedTimeSeconds: 45,
  costMultipliers: {
    quality: { basic: 1, high: 1 },
  },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 1,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/seedream.png",
  modelFamily: "Seedream",
  variantName: "Seedream V4.5",
  displayOrderInFamily: 1,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Seedream_4_5.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "image_urls",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "A text description of the image you want to generate",
      maxLength: 3000,
      renderer: "prompt",
    },
    image_urls: {
      type: "array",
      title: "Input Image",
      description: "Upload an image file to use as input for the API. Formats: JPEG, PNG, WebP. Max size: 10MB",
      renderer: "image",
      items: { type: "string", format: "uri" },
      maxItems: 1,
    },
    aspect_ratio: {
      type: "string",
      title: "Aspect Ratio",
      description: "Width-height ratio of the image, determining its visual form",
      default: "1:1",
      enum: ["1:1", "4:3", "3:4", "16:9", "9:16", "2:3", "3:2", "21:9"],
    },
    quality: {
      type: "string",
      title: "Quality",
      description: "Basic outputs 2K images, while High outputs 4K images",
      default: "high",
      enum: ["basic", "high"],
    },
  },
  required: ["prompt", "image_urls", "aspect_ratio", "quality"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (inputs.prompt.length > 3000) {
    return { valid: false, error: "Prompt must be 3000 characters or less" };
  }

  if (!inputs.image_urls || !Array.isArray(inputs.image_urls) || inputs.image_urls.length === 0) {
    return { valid: false, error: "At least one image URL is required" };
  }

  if (!inputs.aspect_ratio) {
    return { valid: false, error: "Aspect ratio is required" };
  }

  if (!["1:1", "4:3", "3:4", "16:9", "9:16", "2:3", "3:2", "21:9"].includes(inputs.aspect_ratio)) {
    return { valid: false, error: "Invalid aspect_ratio value" };
  }

  if (!inputs.quality) {
    return { valid: false, error: "Quality is required" };
  }

  if (!["basic", "high"].includes(inputs.quality)) {
    return { valid: false, error: "Quality must be basic or high" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    model: MODEL_CONFIG.modelId,
    input: {
      prompt: inputs.prompt,
      image_urls: inputs.image_urls,
      aspect_ratio: inputs.aspect_ratio || "1:1",
      quality: inputs.quality || "basic",
    },
  };
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;

  // Quality multiplier
  const qualityKey = (inputs.quality || "basic") as keyof typeof MODEL_CONFIG.costMultipliers.quality;
  const qualityMult = MODEL_CONFIG.costMultipliers.quality[qualityKey] || 1;

  return Math.round(base * qualityMult * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { prompt, ...modelParameters };

  // Upload images and get URLs if provided
  if (uploadedImages.length > 0) {
    inputs.image_urls = await uploadImagesToStorage(userId);
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    const errorMessage = await extractEdgeFunctionError(funcError);
    throw new Error(errorMessage);
  }

  startPolling(gen.id);
  return gen.id;
}
