/**
 * 🔒 LOCKED MODEL: Seedream V4
 *
 * Group: image_editing
 * Provider: kie_ai
 * Content Type: image
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from "@/lib/models/registry";
import { supabase } from "@/integrations/supabase/client";
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { reserveCredits } from "@/lib/models/creditDeduction";
import { GENERATION_STATUS } from "@/constants/generation-status";
import { sanitizeForStorage } from "@/lib/database/sanitization";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "bytedance/seedream-v4-edit",
  recordId: "57f1e8f3-e4e3-42bd-bd9e-2f2ac6eee41d",
  modelName: "Seedream V4",
  provider: "kie_ai",
  contentType: "image_editing",
  use_api_key: "KIE_AI_API_KEY_IMAGE_EDITING",
  baseCreditCost: 2.5,
  estimatedTimeSeconds: 40,
  costMultipliers: { max_images: { 1: 1, 2: 2, 3: 3, 4: 4 } },
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 10,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/logos/seedream.png",
  modelFamily: "Seedream",
  variantName: "Seedream V4",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/image_editing/Seedream_V4.ts",
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  imageInputField: "image_urls",
  properties: {
    // Required parameters (shown in UI)
    prompt: {
      type: "string",
      title: "Prompt",
      description: "The text prompt used to edit the image",
      maxLength: 5000,
      renderer: "prompt",
    },
    image_urls: {
      type: "array",
      title: "Reference Images",
      description: "List of URLs of input images for editing. Up to 10 images allowed.",
      renderer: "image",
      items: { type: "string", format: "uri" },
      maxItems: 10,
    },
    image_size: {
      type: "string",
      title: "Aspect Ratio",
      description: "The size/aspect ratio of the generated image",
      default: "square",
      enum: [
        "square",
        "square_hd",
        "portrait_4_3",
        "portrait_3_2",
        "portrait_16_9",
        "landscape_4_3",
        "landscape_3_2",
        "landscape_16_9",
        "landscape_21_9",
      ],
    },
    image_resolution: {
      type: "string",
      title: "Resolution",
      description: "Final image resolution.",
      default: "4K",
      enum: ["1K", "2K", "4K"],
    },
    max_images: {
      type: "integer",
      title: "Number of Outputs",
      description: "Number of images to generate (1-4). State the exact number in your prompt for best results.",
      minimum: 1,
      maximum: 4,
      default: 1,
    },

    // Optional/Advanced parameters (hidden from UI)
    seed: {
      type: "integer",
      title: "Seed",
      description: "Random seed to control the stochasticity of image generation",
      showToUser: false,
    },
  },
  required: ["prompt", "image_urls"],
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.prompt) {
    return { valid: false, error: "Prompt is required" };
  }

  if (!inputs.image_urls || !Array.isArray(inputs.image_urls) || inputs.image_urls.length === 0) {
    return { valid: false, error: "At least one image URL is required" };
  }

  if (inputs.image_urls.length > 10) {
    return { valid: false, error: "Maximum 10 images allowed" };
  }

  if (inputs.max_images !== undefined && (inputs.max_images < 1 || inputs.max_images > 6)) {
    return { valid: false, error: "max_images must be between 1 and 6" };
  }

  if (
    inputs.image_size !== undefined &&
    ![
      "square",
      "square_hd",
      "portrait_4_3",
      "portrait_3_2",
      "portrait_16_9",
      "landscape_4_3",
      "landscape_3_2",
      "landscape_16_9",
      "landscape_21_9",
    ].includes(inputs.image_size)
  ) {
    return { valid: false, error: "Invalid image_size value" };
  }

  if (inputs.image_resolution !== undefined && !["1K", "2K", "4K"].includes(inputs.image_resolution)) {
    return { valid: false, error: "image_resolution must be 1K, 2K, or 4K" };
  }

  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  const payload: Record<string, any> = {
    model: MODEL_CONFIG.modelId,
    input: {
      prompt: inputs.prompt,
      image_urls: inputs.image_urls,
      image_size: inputs.image_size || "square",
      image_resolution: inputs.image_resolution || "1K",
      max_images: inputs.max_images || 1,
    },
  };

  // Add optional seed if provided
  if (inputs.seed !== undefined && inputs.seed !== null) {
    payload.input.seed = inputs.seed;
  }

  return payload;
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  const base = MODEL_CONFIG.baseCreditCost;
  const numImages = Math.min(Math.max(inputs.max_images || 1, 1), 4);
  return Math.round(base * numImages * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, uploadedImages, userId, uploadImagesToStorage, startPolling } = params;
  const inputs: Record<string, any> = { ...modelParameters, prompt };

  // Upload images and get URLs if provided
  if (uploadedImages.length > 0) {
    inputs.image_urls = await uploadImagesToStorage(userId);
  }

  // Validate inputs
  const validation = validate(inputs);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Calculate and reserve credits
  const cost = calculateCost(inputs);
  await reserveCredits(userId, cost);

  // Create generation record with pending status (edge function will process)
  const { data: gen, error } = await supabase
    .from("generations")
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      type: getGenerationType(MODEL_CONFIG.contentType),
      prompt,
      tokens_used: cost,
      status: GENERATION_STATUS.PENDING,
      settings: sanitizeForStorage(modelParameters),
    })
    .select()
    .single();

  if (error || !gen) {
    throw new Error(`Failed: ${error?.message}`);
  }

  // Call edge function to handle API call server-side
  // This keeps API keys secure and avoids CORS issues
  const { error: funcError } = await supabase.functions.invoke("generate-content", {
    body: {
      generationId: gen.id,
      model_config: MODEL_CONFIG,
      model_schema: SCHEMA,
      prompt,
      custom_parameters: preparePayload(inputs),
    },
  });

  if (funcError) {
    await supabase.from("generations").update({ status: GENERATION_STATUS.FAILED }).eq("id", gen.id);
    throw new Error(`Edge function failed: ${funcError.message}`);
  }

  startPolling(gen.id);
  return gen.id;
}
