import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { EdgeLogger } from '../_shared/edge-logger.ts';
import { getResponseHeaders, handleCorsPreflight } from "../_shared/cors.ts";



serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return handleCorsPreflight(req);
  }

  const requestId = crypto.randomUUID();
  const startTime = Date.now();

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const logger = new EdgeLogger('seed-azure-voices', requestId, supabaseAdmin, true);
    logger.info('Starting Azure voices seed process');

    // Complete list of all 564 Azure voices from uploaded Excel file
    const voices = [
      { voice_id: 'af-ZA-AdriNeural', voice_name: 'Adri', language: 'Afrikaans', country: 'South Africa', language_code: 'af-ZA' },
      { voice_id: 'af-ZA-WillemNeural', voice_name: 'Willem', language: 'Afrikaans', country: 'South Africa', language_code: 'af-ZA' },
      { voice_id: 'am-ET-MekdesNeural', voice_name: 'Mekdes', language: 'Amharic', country: 'Ethiopia', language_code: 'am-ET' },
      { voice_id: 'am-ET-AmehaNeural', voice_name: 'Ameha', language: 'Amharic', country: 'Ethiopia', language_code: 'am-ET' },
      { voice_id: 'ar-AE-FatimaNeural', voice_name: 'Fatima', language: 'Arabic', country: 'United Arab Emirates', language_code: 'ar-AE' },
      { voice_id: 'ar-AE-HamdanNeural', voice_name: 'Hamdan', language: 'Arabic', country: 'United Arab Emirates', language_code: 'ar-AE' },
      { voice_id: 'ar-BH-LailaNeural', voice_name: 'Laila', language: 'Arabic', country: 'Bahrain', language_code: 'ar-BH' },
      { voice_id: 'ar-BH-AliNeural', voice_name: 'Ali', language: 'Arabic', country: 'Bahrain', language_code: 'ar-BH' },
      { voice_id: 'ar-DZ-AminaNeural', voice_name: 'Amina', language: 'Arabic', country: 'Algeria', language_code: 'ar-DZ' },
      { voice_id: 'ar-DZ-IsmaelNeural', voice_name: 'Ismael', language: 'Arabic', country: 'Algeria', language_code: 'ar-DZ' },
      { voice_id: 'ar-EG-SalmaNeural', voice_name: 'Salma', language: 'Arabic', country: 'Egypt', language_code: 'ar-EG' },
      { voice_id: 'ar-EG-ShakirNeural', voice_name: 'Shakir', language: 'Arabic', country: 'Egypt', language_code: 'ar-EG' },
      { voice_id: 'ar-IQ-RanaNeural', voice_name: 'Rana', language: 'Arabic', country: 'Iraq', language_code: 'ar-IQ' },
      { voice_id: 'ar-IQ-BasselNeural', voice_name: 'Bassel', language: 'Arabic', country: 'Iraq', language_code: 'ar-IQ' },
      { voice_id: 'ar-JO-SanaNeural', voice_name: 'Sana', language: 'Arabic', country: 'Jordan', language_code: 'ar-JO' },
      { voice_id: 'ar-JO-TaimNeural', voice_name: 'Taim', language: 'Arabic', country: 'Jordan', language_code: 'ar-JO' },
      { voice_id: 'ar-KW-NouraNeural', voice_name: 'Noura', language: 'Arabic', country: 'Kuwait', language_code: 'ar-KW' },
      { voice_id: 'ar-KW-FahedNeural', voice_name: 'Fahed', language: 'Arabic', country: 'Kuwait', language_code: 'ar-KW' },
      { voice_id: 'ar-LB-LaylaNeural', voice_name: 'Layla', language: 'Arabic', country: 'Lebanon', language_code: 'ar-LB' },
      { voice_id: 'ar-LB-RamiNeural', voice_name: 'Rami', language: 'Arabic', country: 'Lebanon', language_code: 'ar-LB' },
      { voice_id: 'ar-LY-ImanNeural', voice_name: 'Iman', language: 'Arabic', country: 'Libya', language_code: 'ar-LY' },
      { voice_id: 'ar-LY-OmarNeural', voice_name: 'Omar', language: 'Arabic', country: 'Libya', language_code: 'ar-LY' },
      { voice_id: 'ar-MA-MounaNeural', voice_name: 'Mouna', language: 'Arabic', country: 'Morocco', language_code: 'ar-MA' },
      { voice_id: 'ar-MA-JamalNeural', voice_name: 'Jamal', language: 'Arabic', country: 'Morocco', language_code: 'ar-MA' },
      { voice_id: 'ar-OM-AyshaNeural', voice_name: 'Aysha', language: 'Arabic', country: 'Oman', language_code: 'ar-OM' },
      { voice_id: 'ar-OM-AbdullahNeural', voice_name: 'Abdullah', language: 'Arabic', country: 'Oman', language_code: 'ar-OM' },
      { voice_id: 'ar-QA-AmalNeural', voice_name: 'Amal', language: 'Arabic', country: 'Qatar', language_code: 'ar-QA' },
      { voice_id: 'ar-QA-MoazNeural', voice_name: 'Moaz', language: 'Arabic', country: 'Qatar', language_code: 'ar-QA' },
      { voice_id: 'ar-SA-ZariyahNeural', voice_name: 'Zariyah', language: 'Arabic', country: 'Saudi Arabia', language_code: 'ar-SA' },
      { voice_id: 'ar-SA-HamedNeural', voice_name: 'Hamed', language: 'Arabic', country: 'Saudi Arabia', language_code: 'ar-SA' },
      { voice_id: 'ar-SY-AmanyNeural', voice_name: 'Amany', language: 'Arabic', country: 'Syria', language_code: 'ar-SY' },
      { voice_id: 'ar-SY-LaithNeural', voice_name: 'Laith', language: 'Arabic', country: 'Syria', language_code: 'ar-SY' },
      { voice_id: 'ar-TN-ReemNeural', voice_name: 'Reem', language: 'Arabic', country: 'Tunisia', language_code: 'ar-TN' },
      { voice_id: 'ar-TN-HediNeural', voice_name: 'Hedi', language: 'Arabic', country: 'Tunisia', language_code: 'ar-TN' },
      { voice_id: 'ar-YE-MaryamNeural', voice_name: 'Maryam', language: 'Arabic', country: 'Yemen', language_code: 'ar-YE' },
      { voice_id: 'ar-YE-SalehNeural', voice_name: 'Saleh', language: 'Arabic', country: 'Yemen', language_code: 'ar-YE' },
      { voice_id: 'as-IN-YashicaNeural', voice_name: 'Yashica', language: 'Assamese', country: 'India', language_code: 'as-IN' },
      { voice_id: 'as-IN-PriyomNeural', voice_name: 'Priyom', language: 'Assamese', country: 'India', language_code: 'as-IN' },
      { voice_id: 'az-AZ-BanuNeural', voice_name: 'Banu', language: 'Azerbaijani (Latin)', country: 'Azerbaijan', language_code: 'az-AZ' },
      { voice_id: 'az-AZ-BabekNeural', voice_name: 'Babek', language: 'Azerbaijani (Latin)', country: 'Azerbaijan', language_code: 'az-AZ' },
      { voice_id: 'bg-BG-KalinaNeural', voice_name: 'Kalina', language: 'Bulgarian', country: 'Bulgaria', language_code: 'bg-BG' },
      { voice_id: 'bg-BG-BorislavNeural', voice_name: 'Borislav', language: 'Bulgarian', country: 'Bulgaria', language_code: 'bg-BG' },
      { voice_id: 'bn-BD-NabanitaNeural', voice_name: 'Nabanita', language: 'Bangla', country: 'Bangladesh', language_code: 'bn-BD' },
      { voice_id: 'bn-BD-PradeepNeural', voice_name: 'Pradeep', language: 'Bangla', country: 'Bangladesh', language_code: 'bn-BD' },
      { voice_id: 'bn-IN-TanishaaNeural', voice_name: 'Tanishaa', language: 'Bengali', country: 'India', language_code: 'bn-IN' },
      { voice_id: 'bn-IN-BashkarNeural', voice_name: 'Bashkar', language: 'Bengali', country: 'India', language_code: 'bn-IN' },
      { voice_id: 'bs-BA-VesnaNeural', voice_name: 'Vesna', language: 'Bosnian', country: 'Bosnia and Herzegovina', language_code: 'bs-BA' },
      { voice_id: 'bs-BA-GoranNeural', voice_name: 'Goran', language: 'Bosnian', country: 'Bosnia and Herzegovina', language_code: 'bs-BA' },
      { voice_id: 'ca-ES-JoanaNeural', voice_name: 'Joana', language: 'Catalan', country: 'Spain', language_code: 'ca-ES' },
      { voice_id: 'ca-ES-EnricNeural', voice_name: 'Enric', language: 'Catalan', country: 'Spain', language_code: 'ca-ES' },
      { voice_id: 'ca-ES-AlbaNeural', voice_name: 'Alba', language: 'Catalan', country: 'Spain', language_code: 'ca-ES' },
      { voice_id: 'cs-CZ-VlastaNeural', voice_name: 'Vlasta', language: 'Czech', country: 'Czechia', language_code: 'cs-CZ' },
      { voice_id: 'cs-CZ-AntoninNeural', voice_name: 'Antonin', language: 'Czech', country: 'Czechia', language_code: 'cs-CZ' },
      { voice_id: 'cy-GB-NiaNeural', voice_name: 'Nia', language: 'Welsh', country: 'United Kingdom', language_code: 'cy-GB' },
      { voice_id: 'cy-GB-AledNeural', voice_name: 'Aled', language: 'Welsh', country: 'United Kingdom', language_code: 'cy-GB' },
      { voice_id: 'da-DK-ChristelNeural', voice_name: 'Christel', language: 'Danish', country: 'Denmark', language_code: 'da-DK' },
      { voice_id: 'da-DK-JeppeNeural', voice_name: 'Jeppe', language: 'Danish', country: 'Denmark', language_code: 'da-DK' },
      { voice_id: 'de-AT-IngridNeural', voice_name: 'Ingrid', language: 'German', country: 'Austria', language_code: 'de-AT' },
      { voice_id: 'de-AT-JonasNeural', voice_name: 'Jonas', language: 'German', country: 'Austria', language_code: 'de-AT' },
      { voice_id: 'de-CH-LeniNeural', voice_name: 'Leni', language: 'German', country: 'Switzerland', language_code: 'de-CH' },
      { voice_id: 'de-CH-JanNeural', voice_name: 'Jan', language: 'German', country: 'Switzerland', language_code: 'de-CH' },
      { voice_id: 'de-DE-KatjaNeural', voice_name: 'Katja', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-ConradNeural', voice_name: 'Conrad', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-SeraphinaMultilingualNeural', voice_name: 'Seraphina', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-FlorianMultilingualNeural', voice_name: 'Florian', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-AmalaNeural', voice_name: 'Amala', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-BerndNeural', voice_name: 'Bernd', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-ChristophNeural', voice_name: 'Christoph', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-ElkeNeural', voice_name: 'Elke', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-GiselaNeural', voice_name: 'Gisela', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-KasperNeural', voice_name: 'Kasper', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-KillianNeural', voice_name: 'Killian', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-KlarissaNeural', voice_name: 'Klarissa', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-KlausNeural', voice_name: 'Klaus', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-LouisaNeural', voice_name: 'Louisa', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-MajaNeural', voice_name: 'Maja', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-RalfNeural', voice_name: 'Ralf', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-TanjaNeural', voice_name: 'Tanja', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'de-DE-Seraphina:DragonHDLatestNeural', voice_name: 'Seraphina Dragon HD', language: 'German', country: 'Germany', language_code: 'de-DE' },
      { voice_id: 'el-GR-AthinaNeural', voice_name: 'Athina', language: 'Greek', country: 'Greece', language_code: 'el-GR' },
      { voice_id: 'el-GR-NestorasNeural', voice_name: 'Nestoras', language: 'Greek', country: 'Greece', language_code: 'el-GR' },
      { voice_id: 'en-AU-NatashaNeural', voice_name: 'Natasha', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-WilliamNeural', voice_name: 'William', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-AnnetteNeural', voice_name: 'Annette', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-CarlyNeural', voice_name: 'Carly', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-DarrenNeural', voice_name: 'Darren', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-DuncanNeural', voice_name: 'Duncan', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-ElsieNeural', voice_name: 'Elsie', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-FreyaNeural', voice_name: 'Freya', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-JoanneNeural', voice_name: 'Joanne', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-KenNeural', voice_name: 'Ken', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-KimNeural', voice_name: 'Kim', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-NeilNeural', voice_name: 'Neil', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-TimNeural', voice_name: 'Tim', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-AU-TinaNeural', voice_name: 'Tina', language: 'English', country: 'Australia', language_code: 'en-AU' },
      { voice_id: 'en-CA-ClaraNeural', voice_name: 'Clara', language: 'English', country: 'Canada', language_code: 'en-CA' },
      { voice_id: 'en-CA-LiamNeural', voice_name: 'Liam', language: 'English', country: 'Canada', language_code: 'en-CA' },
      { voice_id: 'en-GB-SoniaNeural', voice_name: 'Sonia', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-RyanNeural', voice_name: 'Ryan', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-LibbyNeural', voice_name: 'Libby', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-AdaMultilingualNeural', voice_name: 'Ada', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-OllieMultilingualNeural', voice_name: 'Ollie', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-AbbiNeural', voice_name: 'Abbi', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-AlfieNeural', voice_name: 'Alfie', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-BellaNeural', voice_name: 'Bella', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-ElliotNeural', voice_name: 'Elliot', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-EthanNeural', voice_name: 'Ethan', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-HollieNeural', voice_name: 'Hollie', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-MaisieNeural', voice_name: 'Maisie', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-NoahNeural', voice_name: 'Noah', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-OliverNeural', voice_name: 'Oliver', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-OliviaNeural', voice_name: 'Olivia', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-ThomasNeural', voice_name: 'Thomas', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-GB-MiaNeural', voice_name: 'Mia', language: 'English', country: 'United Kingdom', language_code: 'en-GB' },
      { voice_id: 'en-HK-YanNeural', voice_name: 'Yan', language: 'English', country: 'Hong Kong SAR', language_code: 'en-HK' },
      { voice_id: 'en-HK-SamNeural', voice_name: 'Sam', language: 'English', country: 'Hong Kong SAR', language_code: 'en-HK' },
      { voice_id: 'en-IE-EmilyNeural', voice_name: 'Emily', language: 'English', country: 'Ireland', language_code: 'en-IE' },
      { voice_id: 'en-IE-ConnorNeural', voice_name: 'Connor', language: 'English', country: 'Ireland', language_code: 'en-IE' },
      { voice_id: 'en-IN-AaravNeural', voice_name: 'Aarav', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-AashiNeural', voice_name: 'Aashi', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-AnanyaNeural', voice_name: 'Ananya', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-KavyaNeural', voice_name: 'Kavya', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-KunalNeural', voice_name: 'Kunal', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-NeerjaNeural', voice_name: 'Neerja', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-PrabhatNeural', voice_name: 'Prabhat', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-RehaanNeural', voice_name: 'Rehaan', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-AartiNeural', voice_name: 'Aarti', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-IN-ArjunNeural', voice_name: 'Arjun', language: 'English', country: 'India', language_code: 'en-IN' },
      { voice_id: 'en-KE-AsiliaNeural', voice_name: 'Asilia', language: 'English', country: 'Kenya', language_code: 'en-KE' },
      { voice_id: 'en-KE-ChilembaNeural', voice_name: 'Chilemba', language: 'English', country: 'Kenya', language_code: 'en-KE' },
      { voice_id: 'en-NG-EzinneNeural', voice_name: 'Ezinne', language: 'English', country: 'Nigeria', language_code: 'en-NG' },
      { voice_id: 'en-NG-AbeoNeural', voice_name: 'Abeo', language: 'English', country: 'Nigeria', language_code: 'en-NG' },
      { voice_id: 'en-NZ-MollyNeural', voice_name: 'Molly', language: 'English', country: 'New Zealand', language_code: 'en-NZ' },
      { voice_id: 'en-NZ-MitchellNeural', voice_name: 'Mitchell', language: 'English', country: 'New Zealand', language_code: 'en-NZ' },
      { voice_id: 'en-PH-RosaNeural', voice_name: 'Rosa', language: 'English', country: 'Philippines', language_code: 'en-PH' },
      { voice_id: 'en-PH-JamesNeural', voice_name: 'James', language: 'English', country: 'Philippines', language_code: 'en-PH' },
      { voice_id: 'en-SG-LunaNeural', voice_name: 'Luna', language: 'English', country: 'Singapore', language_code: 'en-SG' },
      { voice_id: 'en-SG-WayneNeural', voice_name: 'Wayne', language: 'English', country: 'Singapore', language_code: 'en-SG' },
      { voice_id: 'en-TZ-ImaniNeural', voice_name: 'Imani', language: 'English', country: 'Tanzania', language_code: 'en-TZ' },
      { voice_id: 'en-TZ-ElimuNeural', voice_name: 'Elimu', language: 'English', country: 'Tanzania', language_code: 'en-TZ' },
      { voice_id: 'en-US-AvaMultilingualNeural', voice_name: 'Ava', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AndrewMultilingualNeural', voice_name: 'Andrew', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-EmmaMultilingualNeural', voice_name: 'Emma', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-BrianMultilingualNeural', voice_name: 'Brian', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AvaNeural', voice_name: 'Ava', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AndrewNeural', voice_name: 'Andrew', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-EmmaNeural', voice_name: 'Emma', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-BrianNeural', voice_name: 'Brian', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-JennyNeural', voice_name: 'Jenny', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-GuyNeural', voice_name: 'Guy', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AriaNeural', voice_name: 'Aria', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-DavisNeural', voice_name: 'Davis', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-JaneNeural', voice_name: 'Jane', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-JasonNeural', voice_name: 'Jason', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-KaiNeural', voice_name: 'Kai', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-LunaNeural', voice_name: 'Luna', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-SaraNeural', voice_name: 'Sara', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-TonyNeural', voice_name: 'Tony', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-NancyNeural', voice_name: 'Nancy', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-CoraMultilingualNeural', voice_name: 'Cora', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-ChristopherMultilingualNeural', voice_name: 'Christopher', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-BrandonMultilingualNeural', voice_name: 'Brandon', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AmberNeural', voice_name: 'Amber', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AnaNeural', voice_name: 'Ana', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AshleyNeural', voice_name: 'Ashley', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-BrandonNeural', voice_name: 'Brandon', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-ChristopherNeural', voice_name: 'Christopher', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-CoraNeural', voice_name: 'Cora', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-ElizabethNeural', voice_name: 'Elizabeth', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-EricNeural', voice_name: 'Eric', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-JacobNeural', voice_name: 'Jacob', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-JennyMultilingualNeural', voice_name: 'Jenny', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-MichelleNeural', voice_name: 'Michelle', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-MonicaNeural', voice_name: 'Monica', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-RogerNeural', voice_name: 'Roger', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-RyanMultilingualNeural', voice_name: 'Ryan', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-SteffanNeural', voice_name: 'Steffan', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AdamMultilingualNeural', voice_name: 'Adam', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AIGenerate1Neural', voice_name: 'AIGenerate1', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AIGenerate2Neural', voice_name: 'AIGenerate2', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AlloyTurboMultilingualNeural', voice_name: 'Alloy Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-AmandaMultilingualNeural', voice_name: 'Amanda', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-BlueNeural', voice_name: 'Blue', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-DavisMultilingualNeural', voice_name: 'Davis', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-DerekMultilingualNeural', voice_name: 'Derek', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-DustinMultilingualNeural', voice_name: 'Dustin', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-EchoTurboMultilingualNeural', voice_name: 'Echo Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-EvelynMultilingualNeural', voice_name: 'Evelyn', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-FableTurboMultilingualNeural', voice_name: 'Fable Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-LewisMultilingualNeural', voice_name: 'Lewis', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-LolaMultilingualNeural', voice_name: 'Lola', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-NancyMultilingualNeural', voice_name: 'Nancy', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-NovaTurboMultilingualNeural', voice_name: 'Nova Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-OnyxTurboMultilingualNeural', voice_name: 'Onyx Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-PhoebeMultilingualNeural', voice_name: 'Phoebe', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-SamuelMultilingualNeural', voice_name: 'Samuel', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-SerenaMultilingualNeural', voice_name: 'Serena', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-ShimmerTurboMultilingualNeural', voice_name: 'Shimmer Turbo', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-SteffanMultilingualNeural', voice_name: 'Steffan', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Andrew:DragonHDLatestNeural', voice_name: 'Andrew Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Andrew2:DragonHDLatestNeural', voice_name: 'Andrew2 Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Aria:DragonHDLatestNeural', voice_name: 'Aria Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Ava:DragonHDLatestNeural', voice_name: 'Ava Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Brian:DragonHDLatestNeural', voice_name: 'Brian Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Davis:DragonHDLatestNeural', voice_name: 'Davis Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Emma:DragonHDLatestNeural', voice_name: 'Emma Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Emma2:DragonHDLatestNeural', voice_name: 'Emma2 Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Jenny:DragonHDLatestNeural', voice_name: 'Jenny Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-US-Steffan:DragonHDLatestNeural', voice_name: 'Steffan Dragon HD', language: 'English', country: 'United States', language_code: 'en-US' },
      { voice_id: 'en-ZA-LeahNeural', voice_name: 'Leah', language: 'English', country: 'South Africa', language_code: 'en-ZA' },
      { voice_id: 'en-ZA-LukeNeural', voice_name: 'Luke', language: 'English', country: 'South Africa', language_code: 'en-ZA' },
      { voice_id: 'es-AR-ElenaNeural', voice_name: 'Elena', language: 'Spanish', country: 'Argentina', language_code: 'es-AR' },
      { voice_id: 'es-AR-TomasNeural', voice_name: 'Tomas', language: 'Spanish', country: 'Argentina', language_code: 'es-AR' },
      { voice_id: 'es-BO-SofiaNeural', voice_name: 'Sofia', language: 'Spanish', country: 'Bolivia', language_code: 'es-BO' },
      { voice_id: 'es-BO-MarceloNeural', voice_name: 'Marcelo', language: 'Spanish', country: 'Bolivia', language_code: 'es-BO' },
      { voice_id: 'es-CL-CatalinaNeural', voice_name: 'Catalina', language: 'Spanish', country: 'Chile', language_code: 'es-CL' },
      { voice_id: 'es-CL-LorenzoNeural', voice_name: 'Lorenzo', language: 'Spanish', country: 'Chile', language_code: 'es-CL' },
      { voice_id: 'es-CO-SalomeNeural', voice_name: 'Salome', language: 'Spanish', country: 'Colombia', language_code: 'es-CO' },
      { voice_id: 'es-CO-GonzaloNeural', voice_name: 'Gonzalo', language: 'Spanish', country: 'Colombia', language_code: 'es-CO' },
      { voice_id: 'es-CR-MariaNeural', voice_name: 'Maria', language: 'Spanish', country: 'Costa Rica', language_code: 'es-CR' },
      { voice_id: 'es-CR-JuanNeural', voice_name: 'Juan', language: 'Spanish', country: 'Costa Rica', language_code: 'es-CR' },
      { voice_id: 'es-CU-BelkysNeural', voice_name: 'Belkys', language: 'Spanish', country: 'Cuba', language_code: 'es-CU' },
      { voice_id: 'es-CU-ManuelNeural', voice_name: 'Manuel', language: 'Spanish', country: 'Cuba', language_code: 'es-CU' },
      { voice_id: 'es-DO-RamonaNeural', voice_name: 'Ramona', language: 'Spanish', country: 'Dominican Republic', language_code: 'es-DO' },
      { voice_id: 'es-DO-EmilioNeural', voice_name: 'Emilio', language: 'Spanish', country: 'Dominican Republic', language_code: 'es-DO' },
      { voice_id: 'es-EC-AndreaNeural', voice_name: 'Andrea', language: 'Spanish', country: 'Ecuador', language_code: 'es-EC' },
      { voice_id: 'es-EC-LuisNeural', voice_name: 'Luis', language: 'Spanish', country: 'Ecuador', language_code: 'es-EC' },
      { voice_id: 'es-ES-ElviraNeural', voice_name: 'Elvira', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-AlvaroNeural', voice_name: 'Alvaro', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-ArabellaMultilingualNeural', voice_name: 'Arabella', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-IsidoraMultilingualNeural', voice_name: 'Isidora', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-TristanMultilingualNeural', voice_name: 'Tristan', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-XimenaMultilingualNeural', voice_name: 'Ximena', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-AbrilNeural', voice_name: 'Abril', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-ArnauNeural', voice_name: 'Arnau', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-DarioNeural', voice_name: 'Dario', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-EliasNeural', voice_name: 'Elias', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-EstrellaNeural', voice_name: 'Estrella', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-IreneNeural', voice_name: 'Irene', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-LaiaNeural', voice_name: 'Laia', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-LiaNeural', voice_name: 'Lia', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-NilNeural', voice_name: 'Nil', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-SaulNeural', voice_name: 'Saul', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-TeoNeural', voice_name: 'Teo', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-TrianaNeural', voice_name: 'Triana', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-VeraNeural', voice_name: 'Vera', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-ES-XimenaNeural', voice_name: 'Ximena', language: 'Spanish', country: 'Spain', language_code: 'es-ES' },
      { voice_id: 'es-GQ-TeresaNeural', voice_name: 'Teresa', language: 'Spanish', country: 'Equatorial Guinea', language_code: 'es-GQ' },
      { voice_id: 'es-GQ-JavierNeural', voice_name: 'Javier', language: 'Spanish', country: 'Equatorial Guinea', language_code: 'es-GQ' },
      { voice_id: 'es-GT-MartaNeural', voice_name: 'Marta', language: 'Spanish', country: 'Guatemala', language_code: 'es-GT' },
      { voice_id: 'es-GT-AndresNeural', voice_name: 'Andres', language: 'Spanish', country: 'Guatemala', language_code: 'es-GT' },
      { voice_id: 'es-HN-KarlaNeural', voice_name: 'Karla', language: 'Spanish', country: 'Honduras', language_code: 'es-HN' },
      { voice_id: 'es-HN-CarlosNeural', voice_name: 'Carlos', language: 'Spanish', country: 'Honduras', language_code: 'es-HN' },
      { voice_id: 'es-MX-DaliaNeural', voice_name: 'Dalia', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-JorgeNeural', voice_name: 'Jorge', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-BeatrizNeural', voice_name: 'Beatriz', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-CandelaNeural', voice_name: 'Candela', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-CarlotaNeural', voice_name: 'Carlota', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-CecilioNeural', voice_name: 'Cecilio', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-GerardoNeural', voice_name: 'Gerardo', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-LarissaNeural', voice_name: 'Larissa', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-LibertoNeural', voice_name: 'Liberto', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-LucianoNeural', voice_name: 'Luciano', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-MarinaNeural', voice_name: 'Marina', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-NuriaNeural', voice_name: 'Nuria', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-PelayoNeural', voice_name: 'Pelayo', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-RenataNeural', voice_name: 'Renata', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-MX-YagoNeural', voice_name: 'Yago', language: 'Spanish', country: 'Mexico', language_code: 'es-MX' },
      { voice_id: 'es-NI-YolandaNeural', voice_name: 'Yolanda', language: 'Spanish', country: 'Nicaragua', language_code: 'es-NI' },
      { voice_id: 'es-NI-FedericoNeural', voice_name: 'Federico', language: 'Spanish', country: 'Nicaragua', language_code: 'es-NI' },
      { voice_id: 'es-PA-MargaritaNeural', voice_name: 'Margarita', language: 'Spanish', country: 'Panama', language_code: 'es-PA' },
      { voice_id: 'es-PA-RobertoNeural', voice_name: 'Roberto', language: 'Spanish', country: 'Panama', language_code: 'es-PA' },
      { voice_id: 'es-PE-CamilaNeural', voice_name: 'Camila', language: 'Spanish', country: 'Peru', language_code: 'es-PE' },
      { voice_id: 'es-PE-AlexNeural', voice_name: 'Alex', language: 'Spanish', country: 'Peru', language_code: 'es-PE' },
      { voice_id: 'es-PR-KarinaNeural', voice_name: 'Karina', language: 'Spanish', country: 'Puerto Rico', language_code: 'es-PR' },
      { voice_id: 'es-PR-VictorNeural', voice_name: 'Victor', language: 'Spanish', country: 'Puerto Rico', language_code: 'es-PR' },
      { voice_id: 'es-PY-TaniaNeural', voice_name: 'Tania', language: 'Spanish', country: 'Paraguay', language_code: 'es-PY' },
      { voice_id: 'es-PY-MarioNeural', voice_name: 'Mario', language: 'Spanish', country: 'Paraguay', language_code: 'es-PY' },
      { voice_id: 'es-SV-LorenaNeural', voice_name: 'Lorena', language: 'Spanish', country: 'El Salvador', language_code: 'es-SV' },
      { voice_id: 'es-SV-RodrigoNeural', voice_name: 'Rodrigo', language: 'Spanish', country: 'El Salvador', language_code: 'es-SV' },
      { voice_id: 'es-US-PalomaNeural', voice_name: 'Paloma', language: 'Spanish', country: 'United States', language_code: 'es-US' },
      { voice_id: 'es-US-AlonsoNeural', voice_name: 'Alonso', language: 'Spanish', country: 'United States', language_code: 'es-US' },
      { voice_id: 'es-UY-ValentinaNeural', voice_name: 'Valentina', language: 'Spanish', country: 'Uruguay', language_code: 'es-UY' },
      { voice_id: 'es-UY-MateoNeural', voice_name: 'Mateo', language: 'Spanish', country: 'Uruguay', language_code: 'es-UY' },
      { voice_id: 'es-VE-PaolaNeural', voice_name: 'Paola', language: 'Spanish', country: 'Venezuela', language_code: 'es-VE' },
      { voice_id: 'es-VE-SebastianNeural', voice_name: 'Sebastian', language: 'Spanish', country: 'Venezuela', language_code: 'es-VE' },
      { voice_id: 'et-EE-AnuNeural', voice_name: 'Anu', language: 'Estonian', country: 'Estonia', language_code: 'et-EE' },
      { voice_id: 'et-EE-KertNeural', voice_name: 'Kert', language: 'Estonian', country: 'Estonia', language_code: 'et-EE' },
      { voice_id: 'eu-ES-AinhoaNeural', voice_name: 'Ainhoa', language: 'Basque', country: 'Spain', language_code: 'eu-ES' },
      { voice_id: 'eu-ES-AnderNeural', voice_name: 'Ander', language: 'Basque', country: 'Spain', language_code: 'eu-ES' },
      { voice_id: 'fa-IR-DilaraNeural', voice_name: 'Dilara', language: 'Persian', country: 'Iran', language_code: 'fa-IR' },
      { voice_id: 'fa-IR-FaridNeural', voice_name: 'Farid', language: 'Persian', country: 'Iran', language_code: 'fa-IR' },
      { voice_id: 'fi-FI-SelmaNeural', voice_name: 'Selma', language: 'Finnish', country: 'Finland', language_code: 'fi-FI' },
      { voice_id: 'fi-FI-HarriNeural', voice_name: 'Harri', language: 'Finnish', country: 'Finland', language_code: 'fi-FI' },
      { voice_id: 'fi-FI-NooraNeural', voice_name: 'Noora', language: 'Finnish', country: 'Finland', language_code: 'fi-FI' },
      { voice_id: 'fil-PH-BlessicaNeural', voice_name: 'Blessica', language: 'Filipino', country: 'Philippines', language_code: 'fil-PH' },
      { voice_id: 'fil-PH-AngeloNeural', voice_name: 'Angelo', language: 'Filipino', country: 'Philippines', language_code: 'fil-PH' },
      { voice_id: 'fr-BE-CharlineNeural', voice_name: 'Charline', language: 'French', country: 'Belgium', language_code: 'fr-BE' },
      { voice_id: 'fr-BE-GerardNeural', voice_name: 'Gerard', language: 'French', country: 'Belgium', language_code: 'fr-BE' },
      { voice_id: 'fr-CA-SylvieNeural', voice_name: 'Sylvie', language: 'French', country: 'Canada', language_code: 'fr-CA' },
      { voice_id: 'fr-CA-JeanNeural', voice_name: 'Jean', language: 'French', country: 'Canada', language_code: 'fr-CA' },
      { voice_id: 'fr-CA-AntoineNeural', voice_name: 'Antoine', language: 'French', country: 'Canada', language_code: 'fr-CA' },
      { voice_id: 'fr-CA-ThierryNeural', voice_name: 'Thierry', language: 'French', country: 'Canada', language_code: 'fr-CA' },
      { voice_id: 'fr-CH-ArianeNeural', voice_name: 'Ariane', language: 'French', country: 'Switzerland', language_code: 'fr-CH' },
      { voice_id: 'fr-CH-FabriceNeural', voice_name: 'Fabrice', language: 'French', country: 'Switzerland', language_code: 'fr-CH' },
      { voice_id: 'fr-FR-DeniseNeural', voice_name: 'Denise', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-HenriNeural', voice_name: 'Henri', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-VivienneMultilingualNeural', voice_name: 'Vivienne', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-RemyMultilingualNeural', voice_name: 'Remy', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-LucienMultilingualNeural', voice_name: 'Lucien', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-AlainNeural', voice_name: 'Alain', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-BrigitteNeural', voice_name: 'Brigitte', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-CelesteNeural', voice_name: 'Celeste', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-ClaudeNeural', voice_name: 'Claude', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-CoralieNeural', voice_name: 'Coralie', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-EloiseNeural', voice_name: 'Eloise', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-JacquelineNeural', voice_name: 'Jacqueline', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-JeromeNeural', voice_name: 'Jerome', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-JosephineNeural', voice_name: 'Josephine', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-MauriceNeural', voice_name: 'Maurice', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-YvesNeural', voice_name: 'Yves', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'fr-FR-YvetteNeural', voice_name: 'Yvette', language: 'French', country: 'France', language_code: 'fr-FR' },
      { voice_id: 'ga-IE-OrlaNeural', voice_name: 'Orla', language: 'Irish', country: 'Ireland', language_code: 'ga-IE' },
      { voice_id: 'ga-IE-ColmNeural', voice_name: 'Colm', language: 'Irish', country: 'Ireland', language_code: 'ga-IE' },
      { voice_id: 'gl-ES-SabelaNeural', voice_name: 'Sabela', language: 'Galician', country: 'Spain', language_code: 'gl-ES' },
      { voice_id: 'gl-ES-RoiNeural', voice_name: 'Roi', language: 'Galician', country: 'Spain', language_code: 'gl-ES' },
      { voice_id: 'gu-IN-DhwaniNeural', voice_name: 'Dhwani', language: 'Gujarati', country: 'India', language_code: 'gu-IN' },
      { voice_id: 'gu-IN-NiranjanNeural', voice_name: 'Niranjan', language: 'Gujarati', country: 'India', language_code: 'gu-IN' },
      { voice_id: 'he-IL-HilaNeural', voice_name: 'Hila', language: 'Hebrew', country: 'Israel', language_code: 'he-IL' },
      { voice_id: 'he-IL-AvriNeural', voice_name: 'Avri', language: 'Hebrew', country: 'Israel', language_code: 'he-IL' },
      { voice_id: 'hi-IN-AaravNeural', voice_name: 'Aarav', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-AnanyaNeural', voice_name: 'Ananya', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-KavyaNeural', voice_name: 'Kavya', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-KunalNeural', voice_name: 'Kunal', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-RehaanNeural', voice_name: 'Rehaan', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-SwaraNeural', voice_name: 'Swara', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-MadhurNeural', voice_name: 'Madhur', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-AartiNeural', voice_name: 'Aarti', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hi-IN-ArjunNeural', voice_name: 'Arjun', language: 'Hindi', country: 'India', language_code: 'hi-IN' },
      { voice_id: 'hr-HR-GabrijelaNeural', voice_name: 'Gabrijela', language: 'Croatian', country: 'Croatia', language_code: 'hr-HR' },
      { voice_id: 'hr-HR-SreckoNeural', voice_name: 'Srecko', language: 'Croatian', country: 'Croatia', language_code: 'hr-HR' },
      { voice_id: 'hu-HU-NoemiNeural', voice_name: 'Noemi', language: 'Hungarian', country: 'Hungary', language_code: 'hu-HU' },
      { voice_id: 'hu-HU-TamasNeural', voice_name: 'Tamas', language: 'Hungarian', country: 'Hungary', language_code: 'hu-HU' },
      { voice_id: 'hy-AM-AnahitNeural', voice_name: 'Anahit', language: 'Armenian', country: 'Armenia', language_code: 'hy-AM' },
      { voice_id: 'hy-AM-HaykNeural', voice_name: 'Hayk', language: 'Armenian', country: 'Armenia', language_code: 'hy-AM' },
      { voice_id: 'id-ID-GadisNeural', voice_name: 'Gadis', language: 'Indonesian', country: 'Indonesia', language_code: 'id-ID' },
      { voice_id: 'id-ID-ArdiNeural', voice_name: 'Ardi', language: 'Indonesian', country: 'Indonesia', language_code: 'id-ID' },
      { voice_id: 'is-IS-GudrunNeural', voice_name: 'Gudrun', language: 'Icelandic', country: 'Iceland', language_code: 'is-IS' },
      { voice_id: 'is-IS-GunnarNeural', voice_name: 'Gunnar', language: 'Icelandic', country: 'Iceland', language_code: 'is-IS' },
      { voice_id: 'it-IT-ElsaNeural', voice_name: 'Elsa', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-IsabellaNeural', voice_name: 'Isabella', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-DiegoNeural', voice_name: 'Diego', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-AlessioMultilingualNeural', voice_name: 'Alessio', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-IsabellaMultilingualNeural', voice_name: 'Isabella', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-GiuseppeMultilingualNeural', voice_name: 'Giuseppe', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-MarcelloMultilingualNeural', voice_name: 'Marcello', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-BenignoNeural', voice_name: 'Benigno', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-CalimeroNeural', voice_name: 'Calimero', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-CataldoNeural', voice_name: 'Cataldo', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-FabiolaNeural', voice_name: 'Fabiola', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-FiammaNeural', voice_name: 'Fiamma', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-GianniNeural', voice_name: 'Gianni', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-GiuseppeNeural', voice_name: 'Giuseppe', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-ImeldaNeural', voice_name: 'Imelda', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-IrmaNeural', voice_name: 'Irma', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-LisandroNeural', voice_name: 'Lisandro', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-PalmiraNeural', voice_name: 'Palmira', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-PierinaNeural', voice_name: 'Pierina', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'it-IT-RinaldoNeural', voice_name: 'Rinaldo', language: 'Italian', country: 'Italy', language_code: 'it-IT' },
      { voice_id: 'iu-Cans-CA-SiqiniqNeural', voice_name: 'Siqiniq', language: 'Inuktitut (Syllabics)', country: 'Canada', language_code: 'iu-Cans-CA' },
      { voice_id: 'iu-Cans-CA-TaqqiqNeural', voice_name: 'Taqqiq', language: 'Inuktitut (Syllabics)', country: 'Canada', language_code: 'iu-Cans-CA' },
      { voice_id: 'iu-Latn-CA-SiqiniqNeural', voice_name: 'Siqiniq', language: 'Inuktitut (Latin)', country: 'Canada', language_code: 'iu-Latn-CA' },
      { voice_id: 'iu-Latn-CA-TaqqiqNeural', voice_name: 'Taqqiq', language: 'Inuktitut (Latin)', country: 'Canada', language_code: 'iu-Latn-CA' },
      { voice_id: 'ja-JP-NanamiNeural', voice_name: 'Nanami', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-KeitaNeural', voice_name: 'Keita', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-AoiNeural', voice_name: 'Aoi', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-DaichiNeural', voice_name: 'Daichi', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-MayuNeural', voice_name: 'Mayu', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-NaokiNeural', voice_name: 'Naoki', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-ShioriNeural', voice_name: 'Shiori', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-MasaruMultilingualNeural', voice_name: 'Masaru', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'ja-JP-Masaru:DragonHDLatestNeural', voice_name: 'Masaru Dragon HD', language: 'Japanese', country: 'Japan', language_code: 'ja-JP' },
      { voice_id: 'jv-ID-SitiNeural', voice_name: 'Siti', language: 'Javanese (Latin)', country: 'Indonesia', language_code: 'jv-ID' },
      { voice_id: 'jv-ID-DimasNeural', voice_name: 'Dimas', language: 'Javanese (Latin)', country: 'Indonesia', language_code: 'jv-ID' },
      { voice_id: 'ka-GE-EkaNeural', voice_name: 'Eka', language: 'Georgian', country: 'Georgia', language_code: 'ka-GE' },
      { voice_id: 'ka-GE-GiorgiNeural', voice_name: 'Giorgi', language: 'Georgian', country: 'Georgia', language_code: 'ka-GE' },
      { voice_id: 'kk-KZ-AigulNeural', voice_name: 'Aigul', language: 'Kazakh', country: 'Kazakhstan', language_code: 'kk-KZ' },
      { voice_id: 'kk-KZ-DauletNeural', voice_name: 'Daulet', language: 'Kazakh', country: 'Kazakhstan', language_code: 'kk-KZ' },
      { voice_id: 'km-KH-SreymomNeural', voice_name: 'Sreymom', language: 'Khmer', country: 'Cambodia', language_code: 'km-KH' },
      { voice_id: 'km-KH-PisethNeural', voice_name: 'Piseth', language: 'Khmer', country: 'Cambodia', language_code: 'km-KH' },
      { voice_id: 'kn-IN-SapnaNeural', voice_name: 'Sapna', language: 'Kannada', country: 'India', language_code: 'kn-IN' },
      { voice_id: 'kn-IN-GaganNeural', voice_name: 'Gagan', language: 'Kannada', country: 'India', language_code: 'kn-IN' },
      { voice_id: 'ko-KR-SunHiNeural', voice_name: 'Sun-Hi', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-InJoonNeural', voice_name: 'InJoon', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-HyunsuMultilingualNeural', voice_name: 'Hyunsu', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-BongJinNeural', voice_name: 'BongJin', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-GookMinNeural', voice_name: 'GookMin', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-HyunsuNeural', voice_name: 'Hyunsu', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-JiMinNeural', voice_name: 'JiMin', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-SeoHyeonNeural', voice_name: 'SeoHyeon', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-SoonBokNeural', voice_name: 'SoonBok', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'ko-KR-YuJinNeural', voice_name: 'YuJin', language: 'Korean', country: 'Korea', language_code: 'ko-KR' },
      { voice_id: 'lo-LA-KeomanyNeural', voice_name: 'Keomany', language: 'Lao', country: 'Laos', language_code: 'lo-LA' },
      { voice_id: 'lo-LA-ChanthavongNeural', voice_name: 'Chanthavong', language: 'Lao', country: 'Laos', language_code: 'lo-LA' },
      { voice_id: 'lt-LT-OnaNeural', voice_name: 'Ona', language: 'Lithuanian', country: 'Lithuania', language_code: 'lt-LT' },
      { voice_id: 'lt-LT-LeonasNeural', voice_name: 'Leonas', language: 'Lithuanian', country: 'Lithuania', language_code: 'lt-LT' },
      { voice_id: 'lv-LV-EveritaNeural', voice_name: 'Everita', language: 'Latvian', country: 'Latvia', language_code: 'lv-LV' },
      { voice_id: 'lv-LV-NilsNeural', voice_name: 'Nils', language: 'Latvian', country: 'Latvia', language_code: 'lv-LV' },
      { voice_id: 'mk-MK-MarijaNeural', voice_name: 'Marija', language: 'Macedonian', country: 'North Macedonia', language_code: 'mk-MK' },
      { voice_id: 'mk-MK-AleksandarNeural', voice_name: 'Aleksandar', language: 'Macedonian', country: 'North Macedonia', language_code: 'mk-MK' },
      { voice_id: 'ml-IN-SobhanaNeural', voice_name: 'Sobhana', language: 'Malayalam', country: 'India', language_code: 'ml-IN' },
      { voice_id: 'ml-IN-MidhunNeural', voice_name: 'Midhun', language: 'Malayalam', country: 'India', language_code: 'ml-IN' },
      { voice_id: 'mn-MN-YesuiNeural', voice_name: 'Yesui', language: 'Mongolian', country: 'Mongolia', language_code: 'mn-MN' },
      { voice_id: 'mn-MN-BataaNeural', voice_name: 'Bataa', language: 'Mongolian', country: 'Mongolia', language_code: 'mn-MN' },
      { voice_id: 'mr-IN-AarohiNeural', voice_name: 'Aarohi', language: 'Marathi', country: 'India', language_code: 'mr-IN' },
      { voice_id: 'mr-IN-ManoharNeural', voice_name: 'Manohar', language: 'Marathi', country: 'India', language_code: 'mr-IN' },
      { voice_id: 'ms-MY-YasminNeural', voice_name: 'Yasmin', language: 'Malay', country: 'Malaysia', language_code: 'ms-MY' },
      { voice_id: 'ms-MY-OsmanNeural', voice_name: 'Osman', language: 'Malay', country: 'Malaysia', language_code: 'ms-MY' },
      { voice_id: 'mt-MT-GraceNeural', voice_name: 'Grace', language: 'Maltese', country: 'Malta', language_code: 'mt-MT' },
      { voice_id: 'mt-MT-JosephNeural', voice_name: 'Joseph', language: 'Maltese', country: 'Malta', language_code: 'mt-MT' },
      { voice_id: 'my-MM-NilarNeural', voice_name: 'Nilar', language: 'Burmese', country: 'Myanmar', language_code: 'my-MM' },
      { voice_id: 'my-MM-ThihaNeural', voice_name: 'Thiha', language: 'Burmese', country: 'Myanmar', language_code: 'my-MM' },
      { voice_id: 'nb-NO-PernilleNeural', voice_name: 'Pernille', language: 'Norwegian', country: 'Norway', language_code: 'nb-NO' },
      { voice_id: 'nb-NO-FinnNeural', voice_name: 'Finn', language: 'Norwegian', country: 'Norway', language_code: 'nb-NO' },
      { voice_id: 'nb-NO-IselinNeural', voice_name: 'Iselin', language: 'Norwegian', country: 'Norway', language_code: 'nb-NO' },
      { voice_id: 'ne-NP-HemkalaNeural', voice_name: 'Hemkala', language: 'Nepali', country: 'Nepal', language_code: 'ne-NP' },
      { voice_id: 'ne-NP-SagarNeural', voice_name: 'Sagar', language: 'Nepali', country: 'Nepal', language_code: 'ne-NP' },
      { voice_id: 'nl-BE-DenaNeural', voice_name: 'Dena', language: 'Dutch', country: 'Belgium', language_code: 'nl-BE' },
      { voice_id: 'nl-BE-ArnaudNeural', voice_name: 'Arnaud', language: 'Dutch', country: 'Belgium', language_code: 'nl-BE' },
      { voice_id: 'nl-NL-FennaNeural', voice_name: 'Fenna', language: 'Dutch', country: 'Netherlands', language_code: 'nl-NL' },
      { voice_id: 'nl-NL-MaartenNeural', voice_name: 'Maarten', language: 'Dutch', country: 'Netherlands', language_code: 'nl-NL' },
      { voice_id: 'nl-NL-ColetteNeural', voice_name: 'Colette', language: 'Dutch', country: 'Netherlands', language_code: 'nl-NL' },
      { voice_id: 'or-IN-SubhasiniNeural', voice_name: 'Subhasini', language: 'Odia', country: 'India', language_code: 'or-IN' },
      { voice_id: 'or-IN-SukantNeural', voice_name: 'Sukant', language: 'Odia', country: 'India', language_code: 'or-IN' },
      { voice_id: 'pa-IN-OjasNeural', voice_name: 'Ojas', language: 'Punjabi', country: 'India', language_code: 'pa-IN' },
      { voice_id: 'pa-IN-VaaniNeural', voice_name: 'Vaani', language: 'Punjabi', country: 'India', language_code: 'pa-IN' },
      { voice_id: 'pl-PL-AgnieszkaNeural', voice_name: 'Agnieszka', language: 'Polish', country: 'Poland', language_code: 'pl-PL' },
      { voice_id: 'pl-PL-MarekNeural', voice_name: 'Marek', language: 'Polish', country: 'Poland', language_code: 'pl-PL' },
      { voice_id: 'pl-PL-ZofiaNeural', voice_name: 'Zofia', language: 'Polish', country: 'Poland', language_code: 'pl-PL' },
      { voice_id: 'ps-AF-LatifaNeural', voice_name: 'Latifa', language: 'Pashto', country: 'Afghanistan', language_code: 'ps-AF' },
      { voice_id: 'ps-AF-GulNawazNeural', voice_name: 'Gul Nawaz', language: 'Pashto', country: 'Afghanistan', language_code: 'ps-AF' },
      { voice_id: 'pt-BR-FranciscaNeural', voice_name: 'Francisca', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-AntonioNeural', voice_name: 'Antonio', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-MacerioMultilingualNeural', voice_name: 'Macerio', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-ThalitaMultilingualNeural', voice_name: 'Thalita', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-BrendaNeural', voice_name: 'Brenda', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-DonatoNeural', voice_name: 'Donato', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-ElzaNeural', voice_name: 'Elza', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-FabioNeural', voice_name: 'Fabio', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-GiovannaNeural', voice_name: 'Giovanna', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-HumbertoNeural', voice_name: 'Humberto', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-JulioNeural', voice_name: 'Julio', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-LeilaNeural', voice_name: 'Leila', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-LeticiaNeural', voice_name: 'Leticia', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-ManuelaNeural', voice_name: 'Manuela', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-NicolauNeural', voice_name: 'Nicolau', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-ThalitaNeural', voice_name: 'Thalita', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-ValerioNeural', voice_name: 'Valerio', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-BR-YaraNeural', voice_name: 'Yara', language: 'Portuguese', country: 'Brazil', language_code: 'pt-BR' },
      { voice_id: 'pt-PT-RaquelNeural', voice_name: 'Raquel', language: 'Portuguese', country: 'Portugal', language_code: 'pt-PT' },
      { voice_id: 'pt-PT-DuarteNeural', voice_name: 'Duarte', language: 'Portuguese', country: 'Portugal', language_code: 'pt-PT' },
      { voice_id: 'pt-PT-FernandaNeural', voice_name: 'Fernanda', language: 'Portuguese', country: 'Portugal', language_code: 'pt-PT' },
      { voice_id: 'ro-RO-AlinaNeural', voice_name: 'Alina', language: 'Romanian', country: 'Romania', language_code: 'ro-RO' },
      { voice_id: 'ro-RO-EmilNeural', voice_name: 'Emil', language: 'Romanian', country: 'Romania', language_code: 'ro-RO' },
      { voice_id: 'ru-RU-SvetlanaNeural', voice_name: 'Svetlana', language: 'Russian', country: 'Russia', language_code: 'ru-RU' },
      { voice_id: 'ru-RU-DmitryNeural', voice_name: 'Dmitry', language: 'Russian', country: 'Russia', language_code: 'ru-RU' },
      { voice_id: 'ru-RU-DariyaNeural', voice_name: 'Dariya', language: 'Russian', country: 'Russia', language_code: 'ru-RU' },
      { voice_id: 'si-LK-ThiliniNeural', voice_name: 'Thilini', language: 'Sinhala', country: 'Sri Lanka', language_code: 'si-LK' },
      { voice_id: 'si-LK-SameeraNeural', voice_name: 'Sameera', language: 'Sinhala', country: 'Sri Lanka', language_code: 'si-LK' },
      { voice_id: 'sk-SK-ViktoriaNeural', voice_name: 'Viktoria', language: 'Slovak', country: 'Slovakia', language_code: 'sk-SK' },
      { voice_id: 'sk-SK-LukasNeural', voice_name: 'Lukas', language: 'Slovak', country: 'Slovakia', language_code: 'sk-SK' },
      { voice_id: 'sl-SI-PetraNeural', voice_name: 'Petra', language: 'Slovenian', country: 'Slovenia', language_code: 'sl-SI' },
      { voice_id: 'sl-SI-RokNeural', voice_name: 'Rok', language: 'Slovenian', country: 'Slovenia', language_code: 'sl-SI' },
      { voice_id: 'so-SO-UbaxNeural', voice_name: 'Ubax', language: 'Somali', country: 'Somalia', language_code: 'so-SO' },
      { voice_id: 'so-SO-MuuseNeural', voice_name: 'Muuse', language: 'Somali', country: 'Somalia', language_code: 'so-SO' },
      { voice_id: 'sq-AL-AnilaNeural', voice_name: 'Anila', language: 'Albanian', country: 'Albania', language_code: 'sq-AL' },
      { voice_id: 'sq-AL-IlirNeural', voice_name: 'Ilir', language: 'Albanian', country: 'Albania', language_code: 'sq-AL' },
      { voice_id: 'sr-Latn-RS-NicholasNeural', voice_name: 'Nicholas', language: 'Serbian (Latin)', country: 'Serbia', language_code: 'sr-Latn-RS' },
      { voice_id: 'sr-Latn-RS-SophieNeural', voice_name: 'Sophie', language: 'Serbian (Latin)', country: 'Serbia', language_code: 'sr-Latn-RS' },
      { voice_id: 'sr-RS-SophieNeural', voice_name: 'Sophie', language: 'Serbian (Cyrillic)', country: 'Serbia', language_code: 'sr-RS' },
      { voice_id: 'sr-RS-NicholasNeural', voice_name: 'Nicholas', language: 'Serbian (Cyrillic)', country: 'Serbia', language_code: 'sr-RS' },
      { voice_id: 'su-ID-TutiNeural', voice_name: 'Tuti', language: 'Sundanese', country: 'Indonesia', language_code: 'su-ID' },
      { voice_id: 'su-ID-JajangNeural', voice_name: 'Jajang', language: 'Sundanese', country: 'Indonesia', language_code: 'su-ID' },
      { voice_id: 'sv-SE-SofieNeural', voice_name: 'Sofie', language: 'Swedish', country: 'Sweden', language_code: 'sv-SE' },
      { voice_id: 'sv-SE-MattiasNeural', voice_name: 'Mattias', language: 'Swedish', country: 'Sweden', language_code: 'sv-SE' },
      { voice_id: 'sv-SE-HilleviNeural', voice_name: 'Hillevi', language: 'Swedish', country: 'Sweden', language_code: 'sv-SE' },
      { voice_id: 'sw-KE-ZuriNeural', voice_name: 'Zuri', language: 'Swahili', country: 'Kenya', language_code: 'sw-KE' },
      { voice_id: 'sw-KE-RafikiNeural', voice_name: 'Rafiki', language: 'Swahili', country: 'Kenya', language_code: 'sw-KE' },
      { voice_id: 'sw-TZ-RehemaNeural', voice_name: 'Rehema', language: 'Swahili', country: 'Tanzania', language_code: 'sw-TZ' },
      { voice_id: 'sw-TZ-DaudiNeural', voice_name: 'Daudi', language: 'Swahili', country: 'Tanzania', language_code: 'sw-TZ' },
      { voice_id: 'ta-IN-PallaviNeural', voice_name: 'Pallavi', language: 'Tamil', country: 'India', language_code: 'ta-IN' },
      { voice_id: 'ta-IN-ValluvarNeural', voice_name: 'Valluvar', language: 'Tamil', country: 'India', language_code: 'ta-IN' },
      { voice_id: 'ta-LK-SaranyaNeural', voice_name: 'Saranya', language: 'Tamil', country: 'Sri Lanka', language_code: 'ta-LK' },
      { voice_id: 'ta-LK-KumarNeural', voice_name: 'Kumar', language: 'Tamil', country: 'Sri Lanka', language_code: 'ta-LK' },
      { voice_id: 'ta-MY-KaniNeural', voice_name: 'Kani', language: 'Tamil', country: 'Malaysia', language_code: 'ta-MY' },
      { voice_id: 'ta-MY-SuryaNeural', voice_name: 'Surya', language: 'Tamil', country: 'Malaysia', language_code: 'ta-MY' },
      { voice_id: 'ta-SG-VenbaNeural', voice_name: 'Venba', language: 'Tamil', country: 'Singapore', language_code: 'ta-SG' },
      { voice_id: 'ta-SG-AnbuNeural', voice_name: 'Anbu', language: 'Tamil', country: 'Singapore', language_code: 'ta-SG' },
      { voice_id: 'te-IN-ShrutiNeural', voice_name: 'Shruti', language: 'Telugu', country: 'India', language_code: 'te-IN' },
      { voice_id: 'te-IN-MohanNeural', voice_name: 'Mohan', language: 'Telugu', country: 'India', language_code: 'te-IN' },
      { voice_id: 'th-TH-PremwadeeNeural', voice_name: 'Premwadee', language: 'Thai', country: 'Thailand', language_code: 'th-TH' },
      { voice_id: 'th-TH-NiwatNeural', voice_name: 'Niwat', language: 'Thai', country: 'Thailand', language_code: 'th-TH' },
      { voice_id: 'th-TH-AcharaNeural', voice_name: 'Achara', language: 'Thai', country: 'Thailand', language_code: 'th-TH' },
      { voice_id: 'tr-TR-EmelNeural', voice_name: 'Emel', language: 'Turkish', country: 'Turkey', language_code: 'tr-TR' },
      { voice_id: 'tr-TR-AhmetNeural', voice_name: 'Ahmet', language: 'Turkish', country: 'Turkey', language_code: 'tr-TR' },
      { voice_id: 'uk-UA-PolinaNeural', voice_name: 'Polina', language: 'Ukrainian', country: 'Ukraine', language_code: 'uk-UA' },
      { voice_id: 'uk-UA-OstapNeural', voice_name: 'Ostap', language: 'Ukrainian', country: 'Ukraine', language_code: 'uk-UA' },
      { voice_id: 'ur-IN-GulNeural', voice_name: 'Gul', language: 'Urdu', country: 'India', language_code: 'ur-IN' },
      { voice_id: 'ur-IN-SalmanNeural', voice_name: 'Salman', language: 'Urdu', country: 'India', language_code: 'ur-IN' },
      { voice_id: 'ur-PK-UzmaNeural', voice_name: 'Uzma', language: 'Urdu', country: 'Pakistan', language_code: 'ur-PK' },
      { voice_id: 'ur-PK-AsadNeural', voice_name: 'Asad', language: 'Urdu', country: 'Pakistan', language_code: 'ur-PK' },
      { voice_id: 'uz-UZ-MadinaNeural', voice_name: 'Madina', language: 'Uzbek (Latin)', country: 'Uzbekistan', language_code: 'uz-UZ' },
      { voice_id: 'uz-UZ-SardorNeural', voice_name: 'Sardor', language: 'Uzbek (Latin)', country: 'Uzbekistan', language_code: 'uz-UZ' },
      { voice_id: 'vi-VN-HoaiMyNeural', voice_name: 'HoaiMy', language: 'Vietnamese', country: 'Vietnam', language_code: 'vi-VN' },
      { voice_id: 'vi-VN-NamMinhNeural', voice_name: 'NamMinh', language: 'Vietnamese', country: 'Vietnam', language_code: 'vi-VN' },
      { voice_id: 'wuu-CN-XiaotongNeural', voice_name: 'Xiaotong', language: 'Wu Chinese (Simplified)', country: 'China', language_code: 'wuu-CN' },
      { voice_id: 'wuu-CN-YunzheNeural', voice_name: 'Yunzhe', language: 'Wu Chinese (Simplified)', country: 'China', language_code: 'wuu-CN' },
      { voice_id: 'yue-CN-XiaoMinNeural', voice_name: 'XiaoMin', language: 'Cantonese (Simplified)', country: 'China', language_code: 'yue-CN' },
      { voice_id: 'yue-CN-YunSongNeural', voice_name: 'YunSong', language: 'Cantonese (Simplified)', country: 'China', language_code: 'yue-CN' },
      { voice_id: 'zh-CN-XiaoxiaoNeural', voice_name: 'Xiaoxiao', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunxiNeural', voice_name: 'Yunxi', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunjianNeural', voice_name: 'Yunjian', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoyiNeural', voice_name: 'Xiaoyi', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunyangNeural', voice_name: 'Yunyang', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaochenNeural', voice_name: 'Xiaochen', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaochenMultilingualNeural', voice_name: 'Xiaochen', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaohanNeural', voice_name: 'Xiaohan', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaomengNeural', voice_name: 'Xiaomeng', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaomoNeural', voice_name: 'Xiaomo', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoqiuNeural', voice_name: 'Xiaoqiu', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaorouNeural', voice_name: 'Xiaorou', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoruiNeural', voice_name: 'Xiaorui', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoshuangNeural', voice_name: 'Xiaoshuang', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoxiaoDialectsNeural', voice_name: 'Xiaoxiao Dialects', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoxiaoMultilingualNeural', voice_name: 'Xiaoxiao', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoyanNeural', voice_name: 'Xiaoyan', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoyouNeural', voice_name: 'Xiaoyou', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaoyuMultilingualNeural', voice_name: 'Xiaoyu', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-XiaozhenNeural', voice_name: 'Xiaozhen', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunfengNeural', voice_name: 'Yunfeng', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunhaoNeural', voice_name: 'Yunhao', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunjieNeural', voice_name: 'Yunjie', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunxiaNeural', voice_name: 'Yunxia', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunyeNeural', voice_name: 'Yunye', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunyiMultilingualNeural', voice_name: 'Yunyi', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunzeNeural', voice_name: 'Yunze', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunfanMultilingualNeural', voice_name: 'Yunfan', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-YunxiaoMultilingualNeural', voice_name: 'Yunxiao', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-Xiaochen:DragonHDLatestNeural', voice_name: 'Xiaochen Dragon HD', language: 'Mandarin (Simplified)', country: 'China', language_code: 'zh-CN' },
      { voice_id: 'zh-CN-guangxi-YunqiNeural', voice_name: 'Yunqi', language: 'Guangxi Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-guangxi' },
      { voice_id: 'zh-CN-henan-YundengNeural', voice_name: 'Yundeng', language: 'Henan Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-henan' },
      { voice_id: 'zh-CN-liaoning-XiaobeiNeural', voice_name: 'Xiaobei', language: 'Northeastern Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-liaoning' },
      { voice_id: 'zh-CN-liaoning-YunbiaoNeural', voice_name: 'Yunbiao', language: 'Northeastern Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-liaoning' },
      { voice_id: 'zh-CN-shaanxi-XiaoniNeural', voice_name: 'Xiaoni', language: 'Shaanxi Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-shaanxi' },
      { voice_id: 'zh-CN-shandong-YunxiangNeural', voice_name: 'Yunxiang', language: 'Shandong Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-shandong' },
      { voice_id: 'zh-CN-sichuan-YunxiNeural', voice_name: 'Yunxi', language: 'Sichuan Mandarin (Simplified)', country: 'China', language_code: 'zh-CN-sichuan' },
      { voice_id: 'zh-HK-HiuMaanNeural', voice_name: 'HiuMaan', language: 'Cantonese (Traditional)', country: 'Hong Kong', language_code: 'zh-HK' },
      { voice_id: 'zh-HK-WanLungNeural', voice_name: 'WanLung', language: 'Cantonese (Traditional)', country: 'Hong Kong', language_code: 'zh-HK' },
      { voice_id: 'zh-HK-HiuGaaiNeural', voice_name: 'HiuGaai', language: 'Cantonese (Traditional)', country: 'Hong Kong', language_code: 'zh-HK' },
      { voice_id: 'zh-TW-HsiaoChenNeural', voice_name: 'HsiaoChen', language: 'Taiwanese Mandarin (Traditional)', country: 'Taiwan', language_code: 'zh-TW' },
      { voice_id: 'zh-TW-YunJheNeural', voice_name: 'YunJhe', language: 'Taiwanese Mandarin (Traditional)', country: 'Taiwan', language_code: 'zh-TW' },
      { voice_id: 'zh-TW-HsiaoYuNeural', voice_name: 'HsiaoYu', language: 'Taiwanese Mandarin (Traditional)', country: 'Taiwan', language_code: 'zh-TW' },
      { voice_id: 'zu-ZA-ThandoNeural', voice_name: 'Thando', language: 'Zulu', country: 'South Africa', language_code: 'zu-ZA' },
      { voice_id: 'zu-ZA-ThembaNeural', voice_name: 'Themba', language: 'Zulu', country: 'South Africa', language_code: 'zu-ZA' }
    ];

    logger.info('Seeding Azure voices', { metadata: { voiceCount: voices.length } });

    // Upsert all voices (insert or update on conflict)
    const { error } = await supabaseAdmin
      .from('azure_voices')
      .upsert(
        voices.map(voice => ({
          voice_id: voice.voice_id,
          voice_name: voice.voice_name,
          language: voice.language,
          country: voice.country,
          language_code: voice.language_code,
          provider: 'azure',
          tags: {},
          has_preview: false,
          is_active: true
        })),
        { 
          onConflict: 'voice_id',
          ignoreDuplicates: false 
        }
      );

    if (error) {
      logger.error('Error seeding voices', error);
      throw error;
    }

    logger.info('Successfully seeded Azure voices', { metadata: { count: voices.length } });
    logger.logDuration('Seed process completed', startTime);

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `Successfully seeded ${voices.length} Azure voices`,
        count: voices.length 
      }),
      { 
        headers: { ...responseHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );
    const logger = new EdgeLogger('seed-azure-voices', requestId, supabase, true);
    logger.error('Error in seed-azure-voices function', error as Error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        details: 'Failed to seed Azure voices' 
      }),
      { 
        headers: { ...responseHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
