/**
 * 🔒 LOCKED MODEL: ChatGPT 4o-Image
 * 
 * Group: prompt_to_image
 * Provider: kie_ai
 * Content Type: image
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is the single source of truth for this model
 */

import { getGenerationType } from '@/lib/models/registry';
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { supabase } from "@/integrations/supabase/client";
import { logger } from "@/lib/logger";
import { reserveCredits } from "@/lib/models/creditDeduction";

// MODEL CONFIGURATION
export const MODEL_CONFIG = {
  modelId: "4o-image-api",
  recordId: "3b83cee8-6164-4d98-aebe-f4eadcb3da1d",
  modelName: "ChatGPT 4o-Image",
  provider: "kie_ai",
  contentType: "prompt_to_image",
  baseCreditCost: 3,
  estimatedTimeSeconds: 120,
  costMultipliers: { nVariants: { "1": 1, "2": 1.16666, "4": 1.3333 } },
  apiEndpoint: "/api/v1/gpt4o-image/generate",
  payloadStructure: "flat",
  maxImages: 0,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/src/assets/partners/chatgpt.png",
  modelFamily: "OpenAI",
  variantName: "ChatGPT 4o-Image",
  displayOrderInFamily: 2,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/prompt_to_image/ChatGPT_4o_Image.ts"
} as const;

// FROZEN SCHEMA
export const SCHEMA = {
  type: "object",
  properties: {
    nVariants: {
      type: "integer",
      title: "Number of Outputs",
      default: 1,
      enum: [1, 2, 4]
    },
    prompt: {
      type: "string",
      description: "Editing instruction"
    },
    size: {
      type: "string",
      default: "1:1",
      enum: ["1:1", "2:3", "3:2"]
    }
  },
  required: ["size", "prompt"]
};

// VALIDATION
export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.size) return { valid: false, error: "Size is required" };
  if (!inputs.prompt || inputs.prompt.length < 3) return { valid: false, error: "Prompt must be at least 3 characters" };
  return { valid: true };
}

// PAYLOAD PREPARATION
export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    prompt: inputs.prompt,
    size: inputs.size,
    nVariants: inputs.nVariants || 1
  };
}

// COST CALCULATION
export function calculateCost(inputs: Record<string, any>): number {
  let cost = MODEL_CONFIG.baseCreditCost;
  const nVariants = inputs.nVariants || 1;
  const multiplier = MODEL_CONFIG.costMultipliers.nVariants[String(nVariants)] || 1;
  cost *= multiplier;
  return Math.round(cost * 100) / 100;
}

// EXECUTION
export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, userId } = params;
  
  // Validate
  const validation = validate({ ...modelParameters, prompt });
  if (!validation.valid) throw new Error(validation.error);
  
  // Calculate cost
  const cost = calculateCost({ ...modelParameters, prompt });
  
  // Deduct credits
  await reserveCredits(userId, cost);
  
  // Create generation record
  const { data: generation, error: genError } = await supabase
    .from('generations')
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      prompt,
      type: getGenerationType(MODEL_CONFIG.contentType),
      status: 'processing',
      tokens_used: cost,
      settings: modelParameters
    })
    .select()
    .single();

  if (genError || !generation) throw new Error(`Failed to create generation: ${genError?.message}`);

  // Prepare payload
  const payload = preparePayload({ ...modelParameters, prompt });

  // Call KIE.ai API
  try {
    const response = await fetch(`https://api.klingai.com${MODEL_CONFIG.apiEndpoint}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${await getKieApiKey()}`
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) throw new Error(`API call failed: ${response.statusText}`);
    
    const result = await response.json();
    
    // Update generation with task ID
    await supabase
      .from('generations')
      .update({
        provider_task_id: result.taskId,
        provider_request: payload,
        provider_response: result
      })
      .eq('id', generation.id);

    // Start polling
    params.startPolling(generation.id);
    
    return generation.id;
  } catch (error) {
    await supabase
      .from('generations')
      .update({ status: 'failed' })
      .eq('id', generation.id);
    throw error;
  }
}

async function getKieApiKey(): Promise<string> {
  const { data, error } = await supabase.functions.invoke('get-api-key', {
    body: { provider: 'kie_ai' }
  });
  if (error || !data?.apiKey) throw new Error('Failed to get API key');
  return data.apiKey;
}
