import { TextLayer } from './text-overlay';

export interface SocialMediaTemplate {
  id: string;
  name: string;
  platform: string;
  width: number;
  height: number;
  aspectRatio: number;
  description: string;
  textLayers: Array<Omit<TextLayer, 'id'>>;
}

export const socialMediaTemplates: SocialMediaTemplate[] = [
  {
    id: 'instagram-story',
    name: 'Instagram Story',
    platform: 'Instagram',
    width: 1080,
    height: 1920,
    aspectRatio: 9 / 16,
    description: '1080x1920 • 9:16',
    textLayers: [
      {
        text: '@username',
        x: 0.1,
        y: 0.95,
        fontSize: 32,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 0.9,
        strokeWidth: 2,
        strokeColor: '#000000',
        backgroundColor: null,
        padding: 0,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'instagram-post',
    name: 'Instagram Post',
    platform: 'Instagram',
    width: 1080,
    height: 1080,
    aspectRatio: 1,
    description: '1080x1080 • 1:1',
    textLayers: [
      {
        text: 'Add your caption',
        x: 0.5,
        y: 0.9,
        fontSize: 40,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#000000',
        backgroundColor: null,
        padding: 0,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'instagram-reel',
    name: 'Instagram Reel',
    platform: 'Instagram',
    width: 1080,
    height: 1920,
    aspectRatio: 9 / 16,
    description: '1080x1920 • 9:16',
    textLayers: [
      {
        text: 'Swipe up!',
        x: 0.5,
        y: 0.85,
        fontSize: 48,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#000000',
        backgroundColor: '#ff6b6b',
        padding: 16,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'facebook-cover',
    name: 'Facebook Cover',
    platform: 'Facebook',
    width: 1640,
    height: 924,
    aspectRatio: 16 / 9,
    description: '1640x924 • 16:9',
    textLayers: [
      {
        text: 'Your Brand Name',
        x: 0.5,
        y: 0.5,
        fontSize: 72,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 4,
        strokeColor: '#000000',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        padding: 24,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'facebook-post',
    name: 'Facebook Post',
    platform: 'Facebook',
    width: 1200,
    height: 630,
    aspectRatio: 1.91 / 1,
    description: '1200x630 • 1.91:1',
    textLayers: [
      {
        text: 'Engaging headline',
        x: 0.5,
        y: 0.2,
        fontSize: 56,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#000000',
        backgroundColor: null,
        padding: 0,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'twitter-header',
    name: 'Twitter/X Header',
    platform: 'Twitter/X',
    width: 1500,
    height: 500,
    aspectRatio: 3 / 1,
    description: '1500x500 • 3:1',
    textLayers: [
      {
        text: 'Your Name',
        x: 0.25,
        y: 0.5,
        fontSize: 64,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#000000',
        backgroundColor: null,
        padding: 0,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'twitter-post',
    name: 'Twitter/X Post',
    platform: 'Twitter/X',
    width: 1200,
    height: 675,
    aspectRatio: 16 / 9,
    description: '1200x675 • 16:9',
    textLayers: [
      {
        text: 'Breaking News!',
        x: 0.5,
        y: 0.5,
        fontSize: 56,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#1DA1F2',
        backgroundColor: null,
        padding: 0,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'linkedin-post',
    name: 'LinkedIn Post',
    platform: 'LinkedIn',
    width: 1200,
    height: 627,
    aspectRatio: 1.91 / 1,
    description: '1200x627 • 1.91:1',
    textLayers: [
      {
        text: 'Professional Insight',
        x: 0.5,
        y: 0.15,
        fontSize: 48,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 2,
        strokeColor: '#0077B5',
        backgroundColor: 'rgba(0, 119, 181, 0.8)',
        padding: 16,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'youtube-thumbnail',
    name: 'YouTube Thumbnail',
    platform: 'YouTube',
    width: 1280,
    height: 720,
    aspectRatio: 16 / 9,
    description: '1280x720 • 16:9',
    textLayers: [
      {
        text: 'CLICK HERE',
        x: 0.5,
        y: 0.75,
        fontSize: 72,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffff00',
        opacity: 1,
        strokeWidth: 5,
        strokeColor: '#000000',
        backgroundColor: '#FF0000',
        padding: 20,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'pinterest-pin',
    name: 'Pinterest Pin',
    platform: 'Pinterest',
    width: 1000,
    height: 1500,
    aspectRatio: 2 / 3,
    description: '1000x1500 • 2:3',
    textLayers: [
      {
        text: 'Pin-worthy title',
        x: 0.5,
        y: 0.15,
        fontSize: 48,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#ffffff',
        opacity: 1,
        strokeWidth: 3,
        strokeColor: '#000000',
        backgroundColor: '#E60023',
        padding: 16,
        rotation: 0,
        shadowBlur: 0,
        shadowColor: '#000000',
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
];
