/**
 * 🔒 LOCKED MODEL: Eleven Labs Fast
 * 
 * Group: prompt_to_audio
 * Provider: kie_ai
 * Content Type: audio
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 */

import { getGenerationType } from '@/lib/models/registry';
import type { ExecuteGenerationParams } from "@/lib/generation/executeGeneration";
import { supabase } from "@/integrations/supabase/client";
import { reserveCredits } from "@/lib/models/creditDeduction";

export const MODEL_CONFIG = {
  modelId: "elevenlabs/text-to-speech-turbo-2-5",
  recordId: "379f8945-bd7f-48f3-a1bb-9d2e2413234c",
  modelName: "Eleven Labs Fast",
  provider: "kie_ai",
  contentType: "prompt_to_audio",
  baseCreditCost: 1.25,
  estimatedTimeSeconds: 90,
  costMultipliers: {},
  apiEndpoint: "/api/v1/jobs/createTask",
  payloadStructure: "wrapper",
  maxImages: 0,
  defaultOutputs: 1,

  // UI metadata
  isActive: true,
  logoUrl: "/public/logos/elevenlabs.png",
  modelFamily: "ElevenLabs",
  variantName: "Fast",
  displayOrderInFamily: 1,

  // Lock system
  isLocked: true,
  lockedFilePath: "src/lib/models/locked/prompt_to_audio/ElevenLabs_Fast.ts"
} as const;

export const SCHEMA = {
  type: "object",
  properties: {
    text: {
      type: "string",
      title: "Input Text",
      description: "The text to convert to speech",
      maxLength: 5000
    },
    voice: {
      type: "string",
      title: "Input.Voice",
      description: "The voice to use for speech generation",
      default: "Rachel",
      enum: ["Rachel", "Aria", "Roger", "Sarah", "Laura", "Charlie", "George", "Callum", "River", "Liam", "Charlotte", "Alice", "Matilda", "Will", "Jessica", "Eric", "Chris", "Brian", "Daniel", "Lily", "Bill"]
    },
    stability: {
      type: "number",
      title: "Voice stability (0-1)",
      default: 0.5,
      minimum: 0,
      maximum: 1
    },
    similarity_boost: {
      type: "number",
      title: "Similarity boost (0-1)",
      default: 0.75,
      minimum: 0,
      maximum: 1
    },
    style: {
      type: "number",
      title: "Style exaggeration (0-1)",
      default: 0,
      minimum: 0,
      maximum: 1
    },
    speed: {
      type: "number",
      title: "Input.Speed",
      description: "Speech speed (0.7-1.2)",
      default: 1,
      minimum: 0,
      maximum: 1.2
    },
    timestamps: {
      type: "boolean",
      title: "Input.Timestamps",
      description: "Whether to return timestamps for each word in the generated speech",
      default: false,
      enum: [true, false]
    }
  },
  required: ["text"],
  "x-order": ["text", "voice", "stability", "similarity_boost", "style", "speed", "timestamps"]
};

export function validate(inputs: Record<string, any>): { valid: boolean; error?: string } {
  if (!inputs.text || inputs.text.length === 0) return { valid: false, error: "Text is required" };
  if (inputs.text.length > 5000) return { valid: false, error: "Text must be 5000 characters or less" };
  return { valid: true };
}

export function preparePayload(inputs: Record<string, any>): Record<string, any> {
  return {
    text: inputs.text,
    voice: inputs.voice || "Rachel",
    stability: inputs.stability ?? 0.5,
    similarity_boost: inputs.similarity_boost ?? 0.75,
    style: inputs.style ?? 0,
    speed: inputs.speed ?? 1,
    timestamps: inputs.timestamps ?? false
  };
}

export function calculateCost(inputs: Record<string, any>): number {
  return MODEL_CONFIG.baseCreditCost;
}

export async function execute(params: ExecuteGenerationParams): Promise<string> {
  const { prompt, modelParameters, userId } = params;
  const validation = validate({ ...modelParameters, text: prompt });
  if (!validation.valid) throw new Error(validation.error);
  
  const cost = calculateCost({ ...modelParameters, prompt });
  await reserveCredits(userId, cost);
  const { data: generation, error: genError } = await supabase
    .from('generations')
    .insert({
      user_id: userId,
      model_id: MODEL_CONFIG.modelId,
      model_record_id: MODEL_CONFIG.recordId,
      prompt,
      type: getGenerationType(MODEL_CONFIG.contentType),
      status: 'processing',
      tokens_used: cost,
      settings: modelParameters
    })
    .select()
    .single();

  if (genError || !generation) throw new Error(`Failed to create generation: ${genError?.message}`);

  const payload = { task: MODEL_CONFIG.modelId.split('/')[1], input: preparePayload({ ...modelParameters, text: prompt }) };

  try {
    const response = await fetch(`https://api.klingai.com${MODEL_CONFIG.apiEndpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${await getKieApiKey()}` },
      body: JSON.stringify(payload)
    });

    if (!response.ok) throw new Error(`API call failed: ${response.statusText}`);
    const result = await response.json();
    
    await supabase.from('generations').update({
      provider_task_id: result.taskId,
      provider_request: payload,
      provider_response: result
    }).eq('id', generation.id);

    params.startPolling(generation.id);
    return generation.id;
  } catch (error) {
    await supabase.from('generations').update({ status: 'failed' }).eq('id', generation.id);
    throw error;
  }
}

async function getKieApiKey(): Promise<string> {
  const { data, error } = await supabase.functions.invoke('get-api-key', { body: { provider: 'kie_ai' } });
  if (error || !data?.apiKey) throw new Error('Failed to get API key');
  return data.apiKey;
}
