-- Populate cinematic_prompts with 250+ curated prompts (quality_score: 1-5)
INSERT INTO public.cinematic_prompts (prompt, category, source, quality_score, is_active) VALUES
-- FILM NOIR DETECTIVES & DRAMATIC SHADOWS (quality: 5.0 - highest)
('Cinematic close-up portrait of a 1940s hard-boiled detective, harsh single source lighting from above, fedora casting dramatic shadows across weathered face, cigarette smoke wisping through light beam, deep blacks and high contrast, shot on vintage Panavision 50mm, film noir aesthetic', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of a femme fatale in her 30s, venetian blind shadows striping across face, red lipstick and victory rolls hairstyle, mysterious expression, monochromatic with selective color, shot on Arri Alexa, 85mm lens, classic Hollywood noir lighting', 'text_to_image', 'curated', 5.0, true),
('Dramatic portrait of a grizzled private investigator, single lamp lighting creating deep shadows, scotch glass in hand, office window with rain reflections, moody atmosphere, shot on vintage film stock with grain, 50mm lens, high contrast black and white', 'text_to_image', 'curated', 5.0, true),
('Close-up of a 1950s gangster boss, cigar smoke illuminated by desk lamp, sharp suit and fedora, intimidating presence, chiaroscuro lighting, shot on Panavision anamorphic, deep shadows with rim light, classic noir composition', 'text_to_image', 'curated', 5.0, true),
('Portrait of a nightclub singer in film noir style, spotlight from above, sequined dress catching light, melancholic expression, smoky atmosphere, shot on vintage Cooke lenses, dramatic side lighting, monochrome with rich blacks', 'text_to_image', 'curated', 5.0, true),
('Cinematic shot of a corrupt police officer, harsh interrogation room lighting, sweat on brow, moral conflict in eyes, single overhead bulb, shot on Arri Alexa Mini, 35mm lens, gritty noir atmosphere', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of a mysterious woman behind frosted glass, diffused shadows, red lipstick silhouette, 1940s styling, dramatic backlighting, shot on vintage film stock, soft focus with high contrast', 'text_to_image', 'curated', 5.0, true),
('Close-up of a boxer with bruised face, single source gym lighting, determination in eyes, sweat and blood visible, dramatic shadows, shot on Panavision 75mm, noir lighting with rim highlights', 'text_to_image', 'curated', 5.0, true),
('Portrait of a jazz musician in smoky club, stage spotlight creating dramatic shadows, saxophone reflecting light, absorbed in performance, shot on Cooke anamorphic, deep blacks and warm highlights', 'text_to_image', 'curated', 5.0, true),
('Cinematic shot of a reporter in fedora, typewriter keys catching light, desk lamp illumination, cigarette between fingers, 1940s newsroom atmosphere, shot on vintage lenses, high contrast noir style', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of an aging crime boss, leather chair and cigar, window blinds creating striped shadows, commanding presence, shot on Arri Alexa 65, 85mm lens, dramatic chiaroscuro', 'text_to_image', 'curated', 5.0, true),
('Close-up of a getaway driver, dashboard lights reflecting on focused face, night driving scene, noir atmosphere, shot on anamorphic lenses, urban noir lighting with bokeh', 'text_to_image', 'curated', 5.0, true),
('Portrait of a 1940s secretary, desk lamp side lighting, intelligent gaze, period hairstyle and makeup, mysterious aura, shot on vintage Panavision, classic noir composition', 'text_to_image', 'curated', 5.0, true),
('Cinematic shot of a detective examining evidence, desk lamp creating pool of light, magnifying glass catching illumination, absorbed concentration, shot on Cooke lenses, dramatic lighting', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of a bartender polishing glass, backlit bottles creating atmosphere, knowing expression, nightclub ambiance, shot on Arri Alexa, moody noir lighting', 'text_to_image', 'curated', 5.0, true),
('Close-up of a card dealer in underground casino, table lamp illumination, calculating eyes, cigarette smoke patterns, shot on anamorphic 50mm, dramatic noir shadows', 'text_to_image', 'curated', 5.0, true),
('Portrait of a noir protagonist in rain, streetlight backlighting, water droplets on trench coat, melancholic mood, shot on vintage film stock with grain, cinematic noir atmosphere', 'text_to_image', 'curated', 5.0, true),
('Cinematic shot of a witness in shadow, barely visible features, venetian blind light patterns, tension in posture, shot on Panavision anamorphic, high contrast noir style', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of a club owner, velvet booth and low lighting, sharp suit catching highlights, commanding presence, shot on Cooke prime lenses, classic noir aesthetic', 'text_to_image', 'curated', 5.0, true),
('Close-up of a safe cracker concentrating, penlight illumination on focused face, precision and tension, shot on Arri Alexa Mini, dramatic single source lighting', 'text_to_image', 'curated', 5.0, true),
('Portrait of a street hustler under neon signs, colorful lights reflecting on leather jacket, street-smart expression, urban noir setting, shot on anamorphic lenses, modern noir style', 'text_to_image', 'curated', 5.0, true),
('Cinematic shot of a lounge singer at microphone, spotlight creating halo effect, elegant evening gown, emotional performance, shot on Cooke anamorphic, classic noir lighting', 'text_to_image', 'curated', 5.0, true),
('Film noir portrait of a mysterious stranger at bar, single malt whiskey catching light, fedora and trench coat, enigmatic presence, shot on vintage film stock, atmospheric noir mood', 'text_to_image', 'curated', 5.0, true),
('Close-up of a femme fatale lighting cigarette, match flame illuminating dangerous beauty, diamond jewelry sparkling, shot on Panavision 85mm, classic noir aesthetic', 'text_to_image', 'curated', 5.0, true),
('Portrait of a night watchman with flashlight, beam cutting through darkness, weathered face telling stories, industrial noir setting, shot on Arri Alexa, dramatic lighting', 'text_to_image', 'curated', 5.0, true),

-- GOLDEN HOUR NATURAL BEAUTY (quality: 4.5-5.0)
('Cinematic portrait of a woman in golden hour light, soft warm glow on skin, windswept hair catching sunlight, natural makeup, shot on Arri Alexa 65, 85mm lens, shallow depth of field, dreamy bokeh background', 'text_to_image', 'curated', 4.8, true),
('Beautiful outdoor portrait during magic hour, subject backlit by setting sun creating rim light, lens flare adding atmosphere, natural setting, shot on RED Komodo, anamorphic lens, warm color palette', 'text_to_image', 'curated', 4.7, true),
('Golden hour beach portrait, subject silhouetted against orange sky, waves in background, hair blowing in sea breeze, shot on Sony Venice, 50mm lens, cinematic color grading', 'text_to_image', 'curated', 4.6, true),
('Sunset portrait in meadow, golden light filtering through tall grass, subject smiling naturally, wildflowers in foreground, shot on Panavision DXL2, soft focus background, warm tones', 'text_to_image', 'curated', 4.5, true),
('Close-up during golden hour, sun creating natural rim light, freckles and natural beauty emphasized, authentic emotion, shot on Arri Alexa Mini LF, 135mm lens, creamy bokeh', 'text_to_image', 'curated', 4.5, true),
('Portrait at sunset in desert landscape, warm orange light on face, vast sky background, contemplative mood, shot on RED Monstro, anamorphic format, epic cinematic feel', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait in wheat field, subject touching grain, sun low on horizon, natural joy, shot on Panavision Millennium DXL, 75mm lens, warm color science', 'text_to_image', 'curated', 4.5, true),
('Backlit portrait during magic hour, hair glowing with sunlight, soft natural shadows, peaceful expression, shot on Sony Venice 2, shallow depth of field, dreamy aesthetic', 'text_to_image', 'curated', 4.5, true),
('Sunset portrait on rooftop, city skyline background, golden light wrapping around subject, urban golden hour, shot on Arri Alexa 65, anamorphic lens, cinematic framing', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait in forest clearing, dappled sunlight through trees, natural setting, serene mood, shot on RED Raptor, 50mm lens, organic warm tones', 'text_to_image', 'curated', 4.5, true),
('Beach sunset portrait, wet hair and skin catching golden light, ocean spray in background, natural beauty, shot on Panavision DXL2, 85mm lens, warm color palette', 'text_to_image', 'curated', 4.5, true),
('Portrait during last light of day, subject in profile with golden glow, contemplative atmosphere, shot on Sony Venice, anamorphic format, rich warm highlights', 'text_to_image', 'curated', 4.5, true),
('Golden hour mountain portrait, subject on ridge with sun behind, epic landscape, adventurous spirit, shot on RED Monstro, wide lens, dramatic lighting', 'text_to_image', 'curated', 4.5, true),
('Sunset portrait in flower field, poppies catching golden light, subject in flowing dress, dreamy atmosphere, shot on Arri Alexa Mini, 85mm lens, soft focus', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait with lens flare, sun star visible, authentic moment, natural environment, shot on Panavision Millennium, anamorphic, warm organic feel', 'text_to_image', 'curated', 4.5, true),
('Backlit sunset portrait on pier, water reflecting golden light, peaceful mood, shot on Sony Venice 2, 135mm lens, compressed perspective', 'text_to_image', 'curated', 4.5, true),
('Portrait during magic hour in vineyard, grape vines framing subject, warm harvest light, shot on RED Komodo, 50mm lens, rich earth tones', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait on balcony, city lights beginning to glow, transition time, shot on Arri Alexa 65, anamorphic, cinematic urban feel', 'text_to_image', 'curated', 4.5, true),
('Sunset portrait in lavender field, purple flowers contrasting with golden light, serene beauty, shot on Panavision DXL2, shallow depth of field', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait with sun flare, subject laughing naturally, authentic joy, shot on Sony Venice, 85mm lens, warm spontaneous moment', 'text_to_image', 'curated', 4.5, true),
('Magic hour portrait by lake, water reflecting golden sky, peaceful setting, shot on RED Raptor, anamorphic, dreamy atmosphere', 'text_to_image', 'curated', 4.5, true),
('Sunset portrait in olive grove, ancient trees and golden light, Mediterranean mood, shot on Arri Alexa Mini LF, 75mm lens, warm rich tones', 'text_to_image', 'curated', 4.5, true),
('Golden hour portrait on clifftop, wind in hair, dramatic sky background, shot on Panavision Millennium DXL, wide lens, epic scale', 'text_to_image', 'curated', 4.5, true),
('Backlit portrait during last light, silhouette transitioning to golden glow, mysterious mood, shot on Sony Venice 2, anamorphic format', 'text_to_image', 'curated', 4.5, true),
('Portrait at sunset in sand dunes, golden light on textured sand, desert beauty, shot on RED Monstro, 85mm lens, warm minimalist composition', 'text_to_image', 'curated', 4.5, true),

-- HIGH FASHION EDITORIAL (quality: 4.0-4.5)
('High fashion portrait with dramatic makeup, bold editorial styling, perfect skin retouching, professional studio lighting, shot on Hasselblad H6D, 120mm lens, magazine quality', 'text_to_image', 'curated', 4.3, true),
('Editorial beauty close-up, avant-garde makeup design, precise lighting highlighting features, shot on Phase One XF IQ4, macro lens, ultra high resolution', 'text_to_image', 'curated', 4.2, true),
('Vogue style portrait, haute couture fashion, impeccable styling, studio strobes creating dimension, shot on Hasselblad X2D, 90mm lens, editorial perfection', 'text_to_image', 'curated', 4.1, true),
('Fashion editorial portrait, designer clothing, architectural poses, clean white background, shot on Phase One, professional lighting setup, commercial quality', 'text_to_image', 'curated', 4.0, true),
('High fashion beauty shot, flawless skin, dramatic eye makeup, hair by top stylist, shot on Hasselblad H6D, ring light and strobes, magazine cover worthy', 'text_to_image', 'curated', 4.0, true),
('Editorial portrait with geometric makeup, bold fashion statement, modern styling, shot on Phase One XF, 80mm lens, artistic composition', 'text_to_image', 'curated', 4.0, true),
('Luxury fashion portrait, expensive jewelry and clothing, sophisticated lighting, shot on Hasselblad X2D, 120mm lens, high-end commercial', 'text_to_image', 'curated', 4.0, true),
('Beauty editorial close-up, natural glowing skin, subtle makeup perfection, soft studio lighting, shot on Phase One, macro detail, aspirational beauty', 'text_to_image', 'curated', 4.0, true),
('High fashion portrait with wind machine, dynamic hair movement, couture dress, dramatic lighting, shot on Hasselblad H6D, 90mm lens, editorial drama', 'text_to_image', 'curated', 4.0, true),
('Editorial beauty shot, dewy skin texture, fresh natural makeup, perfect retouching, shot on Phase One XF IQ4, 120mm lens, commercial beauty', 'text_to_image', 'curated', 4.0, true),
('Fashion portrait with colored gels, creative lighting design, avant-garde styling, shot on Hasselblad X2D, professional setup, artistic editorial', 'text_to_image', 'curated', 4.0, true),
('High fashion close-up, dramatic contouring, bold lip color, precision lighting, shot on Phase One, 150mm lens, beauty campaign quality', 'text_to_image', 'curated', 4.0, true),
('Editorial portrait in designer suit, corporate fashion, clean professional styling, shot on Hasselblad H6D, white background, commercial sophistication', 'text_to_image', 'curated', 4.0, true),
('Beauty editorial with wet hair look, glossy skin, modern styling, shot on Phase One XF, ring light setup, contemporary fashion', 'text_to_image', 'curated', 4.0, true),
('High fashion portrait with sculptural clothing, architectural design, dramatic shadows, shot on Hasselblad X2D, 90mm lens, artistic fashion', 'text_to_image', 'curated', 4.0, true),
('Editorial beauty shot with graphic eyeliner, bold makeup artistry, perfect skin, shot on Phase One, macro lens, beauty editorial excellence', 'text_to_image', 'curated', 4.0, true),
('Fashion portrait with statement accessories, luxury styling, sophisticated lighting, shot on Hasselblad H6D, 120mm lens, high-end commercial', 'text_to_image', 'curated', 4.0, true),
('High fashion editorial with color blocking, bold styling choices, modern aesthetic, shot on Phase One XF IQ4, professional setup', 'text_to_image', 'curated', 4.0, true),
('Beauty close-up with glossy lips, dewy skin, natural glow, shot on Hasselblad X2D, ring flash, commercial beauty perfection', 'text_to_image', 'curated', 4.0, true),
('Editorial fashion portrait, flowing fabric, dynamic movement, studio strobes freezing motion, shot on Phase One, 80mm lens, editorial energy', 'text_to_image', 'curated', 4.0, true),
('High fashion beauty with metallic makeup, futuristic styling, creative lighting, shot on Hasselblad H6D, 150mm lens, avant-garde editorial', 'text_to_image', 'curated', 4.0, true),
('Fashion editorial with minimal styling, clean aesthetic, perfect lighting, shot on Phase One XF, 90mm lens, modern minimalism', 'text_to_image', 'curated', 4.0, true),
('Beauty portrait with natural freckles, fresh faced beauty, soft retouching, shot on Hasselblad X2D, natural light style studio, authentic beauty', 'text_to_image', 'curated', 4.0, true),
('High fashion with dramatic silhouette, backlit styling, editorial sophistication, shot on Phase One, professional setup, artistic composition', 'text_to_image', 'curated', 4.0, true),
('Editorial beauty with glowing skin, subtle highlights, luxury beauty aesthetic, shot on Hasselblad H6D, 120mm lens, premium commercial', 'text_to_image', 'curated', 4.0, true),

-- VINTAGE HOLLYWOOD GLAMOUR (quality: 3.5-4.0)
('Classic Hollywood glamour portrait, 1950s starlet styling, soft focus, dramatic eye lighting, shot on vintage glass, timeless beauty', 'text_to_image', 'curated', 3.8, true),
('Old Hollywood close-up, victory rolls hairstyle, red lips, butterfly lighting, shot on classic Panavision, black and white perfection', 'text_to_image', 'curated', 3.7, true),
('Vintage movie star portrait, fur stole and diamonds, sophisticated lighting, shot on old film stock simulation, golden age glamour', 'text_to_image', 'curated', 3.6, true),
('1940s Hollywood beauty, elegant styling, soft romantic lighting, shot on vintage lenses, classic cinema aesthetic', 'text_to_image', 'curated', 3.5, true),
('Glamour portrait in style of George Hurrell, dramatic shadows, star quality lighting, shot on classic portrait lens, Hollywood golden age', 'text_to_image', 'curated', 3.5, true),
('Classic movie star close-up, perfect 1950s makeup, soft focus glamour, shot on vintage cinema glass, timeless sophistication', 'text_to_image', 'curated', 3.5, true),
('Hollywood glamour with cigarette holder, elegant pose, dramatic lighting, shot on classic film stock simulation, vintage star power', 'text_to_image', 'curated', 3.5, true),
('Vintage beauty portrait, finger waves hairstyle, classic red lips, old Hollywood lighting, shot on Panavision vintage', 'text_to_image', 'curated', 3.5, true),
('1930s movie star portrait, art deco styling, sophisticated glamour, shot on period-appropriate glass, silver screen beauty', 'text_to_image', 'curated', 3.5, true),
('Classic Hollywood diva, dramatic eye makeup, fur and jewels, Hurrell-style lighting, shot on vintage lenses, star quality', 'text_to_image', 'curated', 3.5, true),
('Golden age glamour portrait, elegant gown, soft romantic lighting, shot on classic cinema lenses, timeless beauty', 'text_to_image', 'curated', 3.5, true),
('Vintage starlet close-up, perfect 1940s styling, dramatic butterfly lighting, shot on old film stock simulation', 'text_to_image', 'curated', 3.5, true),
('Hollywood glamour with pearls, sophisticated 1950s styling, classic portrait lighting, shot on vintage Panavision', 'text_to_image', 'curated', 3.5, true),
('Classic movie star beauty, platinum blonde hair, dramatic shadows, shot on vintage cinema glass, old Hollywood perfection', 'text_to_image', 'curated', 3.5, true),
('1940s glamour portrait, victory rolls and red lips, soft focus romance, shot on classic lenses, vintage sophistication', 'text_to_image', 'curated', 3.5, true),
('Vintage Hollywood close-up, perfect makeup and hair, star lighting setup, shot on period glass, golden age beauty', 'text_to_image', 'curated', 3.5, true),
('Classic glamour with cigarette, elegant pose, dramatic lighting, shot on vintage film stock simulation, old Hollywood style', 'text_to_image', 'curated', 3.5, true),
('1950s movie star portrait, sophisticated styling, soft romantic glow, shot on classic Panavision, timeless elegance', 'text_to_image', 'curated', 3.5, true),
('Hollywood golden age beauty, dramatic eye makeup, fur wrap, Hurrell lighting, shot on vintage lenses', 'text_to_image', 'curated', 3.5, true),
('Vintage starlet glamour, perfect 1940s styling, classic portrait setup, shot on old cinema glass, silver screen beauty', 'text_to_image', 'curated', 3.5, true),
('Classic Hollywood with diamonds, elegant sophistication, dramatic lighting, shot on vintage Panavision, star quality portrait', 'text_to_image', 'curated', 3.5, true),
('1930s glamour close-up, finger waves, red lips, art deco styling, shot on period-appropriate glass', 'text_to_image', 'curated', 3.5, true),
('Old Hollywood beauty portrait, soft focus perfection, romantic lighting, shot on classic lenses, golden age cinema', 'text_to_image', 'curated', 3.5, true),
('Vintage movie star with fan, elegant pose, dramatic shadows, shot on classic film stock simulation', 'text_to_image', 'curated', 3.5, true),
('Hollywood glamour portrait, 1950s styling perfection, soft butterfly lighting, shot on vintage cinema glass, timeless star power', 'text_to_image', 'curated', 3.5, true),

-- MODERN CINEMATIC DRAMA (quality: 3.0-3.5)
('Cinematic portrait with moody lighting, contemporary drama, shallow depth of field, shot on Arri Alexa, 50mm lens, modern film aesthetic', 'text_to_image', 'curated', 3.3, true),
('Modern film portrait, natural lighting with drama, authentic emotion, shot on RED Komodo, anamorphic lens, indie cinema style', 'text_to_image', 'curated', 3.2, true),
('Contemporary cinematic close-up, window light with shadows, real moment captured, shot on Sony Venice, 85mm lens, modern realism', 'text_to_image', 'curated', 3.1, true),
('Dramatic modern portrait, urban setting, available light, shot on Arri Alexa Mini, 35mm lens, contemporary cinema feel', 'text_to_image', 'curated', 3.0, true),
('Cinematic character study, natural drama, subtle color grading, shot on RED Raptor, 50mm lens, modern indie aesthetic', 'text_to_image', 'curated', 3.0, true),
('Modern film portrait with depth, layered lighting, authentic performance, shot on Panavision DXL2, anamorphic, contemporary cinema', 'text_to_image', 'curated', 3.0, true),
('Contemporary dramatic close-up, window light creating mood, shot on Sony Venice 2, 75mm lens, modern filmmaking', 'text_to_image', 'curated', 3.0, true),
('Cinematic portrait in natural environment, available light drama, shot on Arri Alexa 65, wide lens, modern realism', 'text_to_image', 'curated', 3.0, true),
('Modern character portrait, subtle lighting, authentic emotion, shot on RED Monstro, 85mm lens, contemporary film style', 'text_to_image', 'curated', 3.0, true),
('Dramatic modern close-up, urban lighting, real moment, shot on Panavision Millennium, anamorphic, indie cinema aesthetic', 'text_to_image', 'curated', 3.0, true),
('Contemporary cinematic portrait, natural drama, shallow focus, shot on Sony Venice, 50mm lens, modern storytelling', 'text_to_image', 'curated', 3.0, true),
('Modern film character study, window light and shadows, shot on Arri Alexa Mini LF, 135mm lens, intimate cinema', 'text_to_image', 'curated', 3.0, true),
('Cinematic portrait with available light, urban setting, shot on RED Komodo, 35mm lens, contemporary realism', 'text_to_image', 'curated', 3.0, true),
('Modern dramatic portrait, layered natural lighting, shot on Panavision DXL2, 75mm lens, indie film aesthetic', 'text_to_image', 'curated', 3.0, true),
('Contemporary close-up, moody window light, authentic moment, shot on Sony Venice 2, anamorphic, modern cinema', 'text_to_image', 'curated', 3.0, true),
('Cinematic character portrait, natural environment, dramatic available light, shot on Arri Alexa 65, 50mm lens', 'text_to_image', 'curated', 3.0, true),
('Modern film portrait, urban drama, real lighting conditions, shot on RED Raptor, 85mm lens, contemporary indie', 'text_to_image', 'curated', 3.0, true),
('Dramatic contemporary portrait, window light composition, shot on Panavision Millennium, anamorphic, modern storytelling', 'text_to_image', 'curated', 3.0, true),
('Cinematic modern close-up, natural shadows, authentic performance, shot on Sony Venice, 75mm lens, indie aesthetic', 'text_to_image', 'curated', 3.0, true),
('Contemporary character study, available light drama, shot on Arri Alexa Mini, 50mm lens, modern film realism', 'text_to_image', 'curated', 3.0, true),
('Modern cinematic portrait, urban setting, layered lighting, shot on RED Monstro, anamorphic, contemporary cinema', 'text_to_image', 'curated', 3.0, true),
('Dramatic modern portrait, window light and shadows, shot on Panavision DXL2, 85mm lens, indie film style', 'text_to_image', 'curated', 3.0, true),
('Contemporary close-up, natural moody lighting, shot on Sony Venice 2, 135mm lens, modern intimate cinema', 'text_to_image', 'curated', 3.0, true),
('Cinematic character portrait, urban available light, shot on Arri Alexa 65, 75mm lens, contemporary realism', 'text_to_image', 'curated', 3.0, true),
('Modern film portrait, authentic drama, natural lighting, shot on RED Komodo, 50mm lens, indie aesthetic', 'text_to_image', 'curated', 3.0, true),

-- DRAMATIC CHIAROSCURO (quality: 2.5-3.0)
('Chiaroscuro portrait, single source lighting, dramatic light to shadow transition, Rembrandt-inspired, shot on Arri Alexa, 85mm lens, painterly quality', 'text_to_image', 'curated', 2.8, true),
('Dramatic side lighting portrait, deep shadows, highlight on face, classical painting style, shot on RED Monstro, 75mm lens, high contrast', 'text_to_image', 'curated', 2.7, true),
('Low key portrait with single light source, Caravaggio-inspired drama, rich blacks, shot on Panavision DXL2, 50mm lens, artistic chiaroscuro', 'text_to_image', 'curated', 2.6, true),
('Dramatic portrait with harsh shadows, single window light, Renaissance painting aesthetic, shot on Sony Venice, 85mm lens, classical lighting', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro close-up, directional lighting, sculptural shadows, shot on Arri Alexa Mini LF, 135mm lens, dramatic art style', 'text_to_image', 'curated', 2.5, true),
('Low key portrait, single source drama, deep shadow areas, shot on RED Raptor, 75mm lens, Rembrandt lighting', 'text_to_image', 'curated', 2.5, true),
('Dramatic side light portrait, rich contrast, painterly quality, shot on Panavision Millennium, 85mm lens, classical chiaroscuro', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro character study, single light sculpting features, shot on Sony Venice 2, 50mm lens, Renaissance inspired', 'text_to_image', 'curated', 2.5, true),
('Low key dramatic portrait, window light creating shadows, shot on Arri Alexa 65, anamorphic, artistic high contrast', 'text_to_image', 'curated', 2.5, true),
('Portrait with dramatic light fall-off, Caravaggio style, rich blacks and highlights, shot on RED Monstro, 85mm lens', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro close-up, single source creating dimension, shot on Panavision DXL2, 75mm lens, classical painting light', 'text_to_image', 'curated', 2.5, true),
('Dramatic low key portrait, side light emphasizing features, shot on Sony Venice, 135mm lens, Renaissance aesthetic', 'text_to_image', 'curated', 2.5, true),
('Single light portrait, dramatic shadow play, Rembrandt triangle, shot on Arri Alexa Mini, 85mm lens, painterly', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro drama, window light and shadows, classical composition, shot on RED Komodo, 50mm lens, artistic contrast', 'text_to_image', 'curated', 2.5, true),
('Low key character portrait, single source lighting, rich contrast, shot on Panavision Millennium, anamorphic', 'text_to_image', 'curated', 2.5, true),
('Dramatic side lighting close-up, deep shadows, shot on Sony Venice 2, 75mm lens, Caravaggio inspired', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro portrait with single window, classical painting style, shot on Arri Alexa 65, 85mm lens, artistic drama', 'text_to_image', 'curated', 2.5, true),
('Low key dramatic close-up, directional light sculpting, shot on RED Raptor, 135mm lens, Renaissance lighting', 'text_to_image', 'curated', 2.5, true),
('Portrait with harsh chiaroscuro, single source creating mood, shot on Panavision DXL2, 50mm lens, painterly quality', 'text_to_image', 'curated', 2.5, true),
('Dramatic shadow portrait, window light drama, shot on Sony Venice, anamorphic, classical art inspired', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro character study, side light emphasis, shot on Arri Alexa Mini LF, 75mm lens, Rembrandt style', 'text_to_image', 'curated', 2.5, true),
('Low key portrait with strong contrast, single light source, shot on RED Monstro, 85mm lens, dramatic shadows', 'text_to_image', 'curated', 2.5, true),
('Dramatic chiaroscuro close-up, window creating light and shadow, shot on Panavision Millennium, 50mm lens', 'text_to_image', 'curated', 2.5, true),
('Single source portrait, Caravaggio lighting style, rich blacks, shot on Sony Venice 2, 85mm lens, artistic drama', 'text_to_image', 'curated', 2.5, true),
('Chiaroscuro portrait with deep shadows, classical painting light, shot on Arri Alexa 65, anamorphic, high contrast', 'text_to_image', 'curated', 2.5, true),

-- SOFT NATURAL LIGHT (quality: 2.0-2.5)
('Soft natural portrait, diffused window light, gentle shadows, authentic beauty, shot on Arri Alexa, 85mm lens, natural aesthetic', 'text_to_image', 'curated', 2.3, true),
('Portrait in soft daylight, north-facing window, even illumination, shot on Sony Venice, 50mm lens, natural and flattering', 'text_to_image', 'curated', 2.2, true),
('Gentle natural light portrait, sheer curtain diffusion, soft shadows, shot on RED Komodo, 75mm lens, organic feel', 'text_to_image', 'curated', 2.1, true),
('Soft window portrait, natural skin tones, subtle modeling, shot on Panavision DXL2, 85mm lens, gentle lighting', 'text_to_image', 'curated', 2.0, true),
('Natural light close-up, diffused daylight, soft features, shot on Arri Alexa Mini, 135mm lens, authentic beauty', 'text_to_image', 'curated', 2.0, true),
('Portrait with soft natural illumination, window light wrapping around subject, shot on Sony Venice 2, 50mm lens', 'text_to_image', 'curated', 2.0, true),
('Gentle daylight portrait, natural diffusion, flattering shadows, shot on RED Raptor, 85mm lens, organic lighting', 'text_to_image', 'curated', 2.0, true),
('Soft natural window light, authentic skin texture, gentle modeling, shot on Panavision Millennium, 75mm lens', 'text_to_image', 'curated', 2.0, true),
('Natural portrait with diffused light, soft and even, shot on Arri Alexa 65, 50mm lens, gentle aesthetic', 'text_to_image', 'curated', 2.0, true),
('Window light portrait, sheer diffusion, natural beauty, shot on Sony Venice, anamorphic, soft flattering light', 'text_to_image', 'curated', 2.0, true),
('Soft natural close-up, gentle window illumination, authentic features, shot on RED Monstro, 85mm lens', 'text_to_image', 'curated', 2.0, true),
('Natural daylight portrait, diffused and even, subtle shadows, shot on Panavision DXL2, 135mm lens, organic', 'text_to_image', 'curated', 2.0, true),
('Gentle natural light, soft window glow, flattering on skin, shot on Arri Alexa Mini LF, 75mm lens', 'text_to_image', 'curated', 2.0, true),
('Soft portrait in natural light, curtain diffusion, even illumination, shot on Sony Venice 2, 50mm lens', 'text_to_image', 'curated', 2.0, true),
('Natural window portrait, gentle shadows, authentic beauty, shot on RED Komodo, 85mm lens, soft aesthetic', 'text_to_image', 'curated', 2.0, true),
('Diffused daylight close-up, natural skin tones, soft modeling, shot on Panavision Millennium, anamorphic', 'text_to_image', 'curated', 2.0, true),
('Soft natural portrait, north window light, even and flattering, shot on Arri Alexa 65, 85mm lens', 'text_to_image', 'curated', 2.0, true),
('Gentle natural illumination, window with sheers, subtle shadows, shot on Sony Venice, 135mm lens', 'text_to_image', 'curated', 2.0, true),
('Natural light portrait, soft diffusion, authentic feel, shot on RED Raptor, 50mm lens, organic beauty', 'text_to_image', 'curated', 2.0, true),
('Soft window light close-up, natural and flattering, gentle modeling, shot on Panavision DXL2, 75mm lens', 'text_to_image', 'curated', 2.0, true),
('Diffused natural portrait, soft even light, authentic skin, shot on Arri Alexa Mini, 85mm lens', 'text_to_image', 'curated', 2.0, true),
('Gentle daylight close-up, curtain diffusion, natural beauty, shot on Sony Venice 2, anamorphic', 'text_to_image', 'curated', 2.0, true),
('Natural window portrait, soft and even, flattering illumination, shot on RED Monstro, 50mm lens', 'text_to_image', 'curated', 2.0, true),
('Soft natural light, diffused daylight, gentle on features, shot on Panavision Millennium, 85mm lens', 'text_to_image', 'curated', 2.0, true),
('Natural portrait with sheer window, soft modeling, authentic aesthetic, shot on Arri Alexa 65, 75mm lens', 'text_to_image', 'curated', 2.0, true),

-- URBAN NIGHTSCAPE (quality: 1.5-2.0)
('Urban night portrait, neon lights reflecting on face, city bokeh background, shot on Sony Venice, 50mm lens, modern night aesthetic', 'text_to_image', 'curated', 1.8, true),
('Portrait in city at night, street lights and signs, urban atmosphere, shot on Arri Alexa, 85mm lens, contemporary nighttime', 'text_to_image', 'curated', 1.7, true),
('Night city portrait, colored neon lighting, urban energy, shot on RED Komodo, anamorphic, modern street style', 'text_to_image', 'curated', 1.6, true),
('Urban nighttime close-up, city lights bokeh, neon accents on face, shot on Panavision DXL2, 75mm lens, night vibes', 'text_to_image', 'curated', 1.5, true),
('Portrait in neon-lit street, urban night colors, city atmosphere, shot on Sony Venice 2, 50mm lens, modern nightscape', 'text_to_image', 'curated', 1.5, true),
('Night urban portrait, street lighting and reflections, contemporary city, shot on Arri Alexa Mini, 85mm lens', 'text_to_image', 'curated', 1.5, true),
('City night close-up, neon signs illuminating subject, urban cool, shot on RED Raptor, anamorphic, night aesthetic', 'text_to_image', 'curated', 1.5, true),
('Portrait under city lights, urban night glow, modern atmosphere, shot on Panavision Millennium, 75mm lens', 'text_to_image', 'curated', 1.5, true),
('Neon-lit urban portrait, night city bokeh, contemporary style, shot on Sony Venice, 135mm lens, urban nights', 'text_to_image', 'curated', 1.5, true),
('Night street portrait, colored lighting, urban energy, shot on Arri Alexa 65, 50mm lens, modern city vibe', 'text_to_image', 'curated', 1.5, true),
('Urban nightscape close-up, neon reflections, city atmosphere, shot on RED Monstro, 85mm lens, night portrait', 'text_to_image', 'curated', 1.5, true),
('Portrait in city at night, street signs and lights, shot on Panavision DXL2, anamorphic, urban nocturnal', 'text_to_image', 'curated', 1.5, true),
('Night urban portrait, neon accents, contemporary city life, shot on Sony Venice 2, 75mm lens, modern nighttime', 'text_to_image', 'curated', 1.5, true),
('City night close-up, urban lighting, neon bokeh background, shot on Arri Alexa Mini LF, 50mm lens', 'text_to_image', 'curated', 1.5, true),
('Portrait under neon lights, urban night aesthetic, shot on RED Komodo, 85mm lens, contemporary street', 'text_to_image', 'curated', 1.5, true),
('Night city portrait, colored light sources, urban atmosphere, shot on Panavision Millennium, anamorphic', 'text_to_image', 'curated', 1.5, true),
('Urban nightscape portrait, neon reflections on face, shot on Sony Venice, 135mm lens, modern city nights', 'text_to_image', 'curated', 1.5, true),
('Night street close-up, urban lights and energy, shot on Arri Alexa 65, 75mm lens, contemporary nighttime', 'text_to_image', 'curated', 1.5, true),
('Portrait in neon city, urban night colors, modern vibe, shot on RED Raptor, 50mm lens, night aesthetic', 'text_to_image', 'curated', 1.5, true),
('City nighttime portrait, street lighting atmosphere, shot on Panavision DXL2, 85mm lens, urban nocturnal', 'text_to_image', 'curated', 1.5, true),
('Urban night close-up, neon signs and bokeh, contemporary city, shot on Sony Venice 2, anamorphic', 'text_to_image', 'curated', 1.5, true),
('Night portrait in city, colored urban lighting, modern atmosphere, shot on Arri Alexa Mini, 50mm lens', 'text_to_image', 'curated', 1.5, true),
('Neon-lit street portrait, urban night energy, shot on RED Monstro, 85mm lens, contemporary nightscape', 'text_to_image', 'curated', 1.5, true),
('City night portrait, urban glow and reflections, shot on Panavision Millennium, 75mm lens, night vibes', 'text_to_image', 'curated', 1.5, true),
('Urban nighttime close-up, neon colors on face, city bokeh, shot on Sony Venice, 135mm lens, modern nights', 'text_to_image', 'curated', 1.5, true),

-- CHARACTER STUDIES (quality: 1.0-1.5)
('Character portrait emphasizing weathered features, life experience in face, natural lighting revealing texture, shot on Arri Alexa, 85mm lens, documentary style', 'text_to_image', 'curated', 1.3, true),
('Close-up character study, authentic emotion, imperfect real beauty, shot on Sony Venice, 50mm lens, honest portraiture', 'text_to_image', 'curated', 1.2, true),
('Portrait revealing character through expression, genuine moment, natural environment, shot on RED Komodo, 75mm lens, storytelling portrait', 'text_to_image', 'curated', 1.1, true),
('Character close-up, life lines and authenticity, available light, shot on Panavision DXL2, 85mm lens, real person aesthetic', 'text_to_image', 'curated', 1.0, true),
('Honest character portrait, natural features, genuine expression, shot on Arri Alexa Mini, 135mm lens, documentary style', 'text_to_image', 'curated', 1.0, true),
('Portrait emphasizing personality, authentic character, natural lighting, shot on Sony Venice 2, 50mm lens, real beauty', 'text_to_image', 'curated', 1.0, true),
('Character study showing emotion, life experience visible, shot on RED Raptor, 85mm lens, honest portraiture', 'text_to_image', 'curated', 1.0, true),
('Close-up revealing character, natural imperfections, authentic moment, shot on Panavision Millennium, 75mm lens', 'text_to_image', 'curated', 1.0, true),
('Portrait of real person, character in features, natural lighting, shot on Arri Alexa 65, 50mm lens, documentary', 'text_to_image', 'curated', 1.0, true),
('Character portrait with authentic expression, life story in face, shot on Sony Venice, anamorphic, real aesthetic', 'text_to_image', 'curated', 1.0, true),
('Honest character close-up, natural features, genuine emotion, shot on RED Monstro, 85mm lens, storytelling', 'text_to_image', 'curated', 1.0, true),
('Portrait emphasizing individual character, authentic beauty, shot on Panavision DXL2, 135mm lens, documentary style', 'text_to_image', 'curated', 1.0, true),
('Character study in natural light, real person, honest portraiture, shot on Arri Alexa Mini LF, 75mm lens', 'text_to_image', 'curated', 1.0, true),
('Close-up showing personality, weathered character, authentic moment, shot on Sony Venice 2, 50mm lens', 'text_to_image', 'curated', 1.0, true),
('Portrait revealing individual story, natural features, shot on RED Komodo, 85mm lens, real beauty', 'text_to_image', 'curated', 1.0, true),
('Character portrait with life experience, honest expression, shot on Panavision Millennium, anamorphic, documentary', 'text_to_image', 'curated', 1.0, true),
('Authentic character close-up, natural imperfections, genuine emotion, shot on Arri Alexa 65, 85mm lens', 'text_to_image', 'curated', 1.0, true),
('Portrait emphasizing real character, personality in features, shot on Sony Venice, 135mm lens, honest style', 'text_to_image', 'curated', 1.0, true),
('Character study showing authenticity, natural light, real person, shot on RED Raptor, 50mm lens, documentary', 'text_to_image', 'curated', 1.0, true),
('Close-up of individual character, weathered beauty, shot on Panavision DXL2, 75mm lens, storytelling portrait', 'text_to_image', 'curated', 1.0, true),
('Portrait revealing authentic personality, natural features, shot on Arri Alexa Mini, 85mm lens, real aesthetic', 'text_to_image', 'curated', 1.0, true),
('Character portrait with genuine expression, life in face, shot on Sony Venice 2, anamorphic, honest portraiture', 'text_to_image', 'curated', 1.0, true),
('Authentic character study, natural imperfections, real beauty, shot on RED Monstro, 50mm lens, documentary', 'text_to_image', 'curated', 1.0, true),
('Portrait emphasizing individual story, honest features, shot on Panavision Millennium, 85mm lens, real person', 'text_to_image', 'curated', 1.0, true),
('Character close-up showing personality, authentic moment, shot on Arri Alexa 65, 75mm lens, storytelling style', 'text_to_image', 'curated', 1.0, true),

-- ANAMORPHIC CINEMA (quality: 1.0)
('Cinematic anamorphic portrait, 2.39:1 aspect ratio, oval bokeh, horizontal lens flares, shot on Panavision anamorphic, epic cinema feel', 'text_to_image', 'curated', 1.0, true),
('Portrait with anamorphic characteristics, wide format, distinctive bokeh, shot on Arri Alexa with anamorphic lens, theatrical quality', 'text_to_image', 'curated', 1.0, true),
('Anamorphic close-up, horizontal flares, cinematic bokeh, shot on Panavision C-series, 2.40:1 format, movie aesthetic', 'text_to_image', 'curated', 1.0, true),
('Wide format portrait, anamorphic lens characteristics, oval bokeh background, shot on Hawk anamorphic, cinematic feel', 'text_to_image', 'curated', 1.0, true),
('Cinematic anamorphic portrait, 2.39 aspect ratio, distinctive lens flares, shot on Panavision G-series, theatrical look', 'text_to_image', 'curated', 1.0, true),
('Portrait in anamorphic format, horizontal bokeh, wide cinematic frame, shot on Arri Alexa with Hawk lenses', 'text_to_image', 'curated', 1.0, true),
('Anamorphic close-up, oval out-of-focus areas, horizontal flares, shot on Panavision anamorphic, movie quality', 'text_to_image', 'curated', 1.0, true),
('Wide format cinematic portrait, anamorphic bokeh, 2.40:1 ratio, shot on Cooke anamorphic, theatrical aesthetic', 'text_to_image', 'curated', 1.0, true),
('Portrait with anamorphic lens, distinctive horizontal elements, shot on Panavision T-series, cinema format', 'text_to_image', 'curated', 1.0, true),
('Anamorphic portrait, oval bokeh background, wide cinematic framing, shot on Arri Alexa with Panavision glass', 'text_to_image', 'curated', 1.0, true),
('Cinematic close-up in anamorphic, horizontal lens characteristics, shot on Hawk V-Lite, 2.39:1 format', 'text_to_image', 'curated', 1.0, true),
('Wide format portrait, anamorphic bokeh style, movie aspect ratio, shot on Panavision C-series anamorphic', 'text_to_image', 'curated', 1.0, true),
('Anamorphic cinematic portrait, horizontal flare elements, shot on Cooke anamorphic, theatrical framing', 'text_to_image', 'curated', 1.0, true),
('Portrait in 2.40:1 format, anamorphic lens characteristics, shot on Arri Alexa with Panavision', 'text_to_image', 'curated', 1.0, true),
('Cinematic anamorphic close-up, oval bokeh, horizontal elements, shot on Hawk anamorphic lenses', 'text_to_image', 'curated', 1.0, true),
('Wide format portrait with anamorphic look, distinctive bokeh, shot on Panavision G-series, cinema aesthetic', 'text_to_image', 'curated', 1.0, true),
('Anamorphic portrait, 2.39 aspect ratio, horizontal flares, shot on Cooke anamorphic, theatrical quality', 'text_to_image', 'curated', 1.0, true),
('Portrait in anamorphic format, oval out-of-focus areas, shot on Arri Alexa with Hawk glass', 'text_to_image', 'curated', 1.0, true),
('Cinematic wide portrait, anamorphic characteristics, movie framing, shot on Panavision T-series anamorphic', 'text_to_image', 'curated', 1.0, true),
('Anamorphic close-up, horizontal bokeh, cinematic format, shot on Hawk V-Lite anamorphic lenses', 'text_to_image', 'curated', 1.0, true),
('Wide format portrait, anamorphic lens look, 2.40:1 ratio, shot on Panavision C-series, theatrical', 'text_to_image', 'curated', 1.0, true),
('Portrait with anamorphic bokeh, horizontal flare elements, shot on Cooke anamorphic, cinema feel', 'text_to_image', 'curated', 1.0, true),
('Anamorphic cinematic portrait, oval bokeh background, shot on Arri Alexa with Panavision anamorphic', 'text_to_image', 'curated', 1.0, true),
('Wide format close-up, anamorphic characteristics, movie aspect, shot on Hawk anamorphic glass', 'text_to_image', 'curated', 1.0, true),
('Portrait in anamorphic 2.39:1, horizontal lens elements, shot on Panavision G-series, theatrical aesthetic', 'text_to_image', 'curated', 1.0, true);