-- Add remaining 100+ prompts to reach 250+ total
INSERT INTO public.cinematic_prompts (prompt, category, source, quality_score, is_active) VALUES
-- More Film Noir (15 prompts)
('Close-up of a 1950s gangster boss, cigar smoke illuminated by desk lamp, sharp suit and fedora, intimidating presence, chiaroscuro lighting, shot on Panavision anamorphic, deep shadows with rim light, classic noir composition', 'text_to_image', 'curated', 5, true),
('Film noir portrait of a mysterious woman behind frosted glass, diffused shadows, red lipstick silhouette, 1940s styling, dramatic backlighting, shot on vintage film stock, soft focus with high contrast', 'text_to_image', 'curated', 5, true),
('Close-up of a boxer with bruised face, single source gym lighting, determination in eyes, sweat and blood visible, dramatic shadows, shot on Panavision 75mm, noir lighting with rim highlights', 'text_to_image', 'curated', 5, true),
('Portrait of a jazz musician in smoky club, stage spotlight creating dramatic shadows, saxophone reflecting light, absorbed in performance, shot on Cooke anamorphic, deep blacks and warm highlights', 'text_to_image', 'curated', 5, true),
('Cinematic shot of a reporter in fedora, typewriter keys catching light, desk lamp illumination, cigarette between fingers, 1940s newsroom atmosphere, shot on vintage lenses, high contrast noir style', 'text_to_image', 'curated', 5, true),
('Film noir portrait of an aging crime boss, leather chair and cigar, window blinds creating striped shadows, commanding presence, shot on Arri Alexa 65, 85mm lens, dramatic chiaroscuro', 'text_to_image', 'curated', 5, true),
('Close-up of a getaway driver, dashboard lights reflecting on focused face, night driving scene, noir atmosphere, shot on anamorphic lenses, urban noir lighting with bokeh', 'text_to_image', 'curated', 5, true),
('Portrait of a 1940s secretary, desk lamp side lighting, intelligent gaze, period hairstyle and makeup, mysterious aura, shot on vintage Panavision, classic noir composition', 'text_to_image', 'curated', 5, true),
('Cinematic shot of a detective examining evidence, desk lamp creating pool of light, magnifying glass catching illumination, absorbed concentration, shot on Cooke lenses, dramatic lighting', 'text_to_image', 'curated', 5, true),
('Film noir portrait of a bartender polishing glass, backlit bottles creating atmosphere, knowing expression, nightclub ambiance, shot on Arri Alexa, moody noir lighting', 'text_to_image', 'curated', 5, true),
('Close-up of a card dealer in underground casino, table lamp illumination, calculating eyes, cigarette smoke patterns, shot on anamorphic 50mm, dramatic noir shadows', 'text_to_image', 'curated', 5, true),
('Portrait of a noir protagonist in rain, streetlight backlighting, water droplets on trench coat, melancholic mood, shot on vintage film stock with grain, cinematic noir atmosphere', 'text_to_image', 'curated', 5, true),
('Cinematic shot of a witness in shadow, barely visible features, venetian blind light patterns, tension in posture, shot on Panavision anamorphic, high contrast noir style', 'text_to_image', 'curated', 5, true),
('Film noir portrait of a club owner, velvet booth and low lighting, sharp suit catching highlights, commanding presence, shot on Cooke prime lenses, classic noir aesthetic', 'text_to_image', 'curated', 5, true),
('Close-up of a safe cracker concentrating, penlight illumination on focused face, precision and tension, shot on Arri Alexa Mini, dramatic single source lighting', 'text_to_image', 'curated', 5, true),

-- More Golden Hour (15 prompts)
('Golden hour beach portrait, subject silhouetted against orange sky, waves in background, hair blowing in sea breeze, shot on Sony Venice, 50mm lens, cinematic color grading', 'text_to_image', 'curated', 4, true),
('Sunset portrait in meadow, golden light filtering through tall grass, subject smiling naturally, wildflowers in foreground, shot on Panavision DXL2, soft focus background, warm tones', 'text_to_image', 'curated', 4, true),
('Close-up during golden hour, sun creating natural rim light, freckles and natural beauty emphasized, authentic emotion, shot on Arri Alexa Mini LF, 135mm lens, creamy bokeh', 'text_to_image', 'curated', 4, true),
('Portrait at sunset in desert landscape, warm orange light on face, vast sky background, contemplative mood, shot on RED Monstro, anamorphic format, epic cinematic feel', 'text_to_image', 'curated', 4, true),
('Golden hour portrait in wheat field, subject touching grain, sun low on horizon, natural joy, shot on Panavision Millennium DXL, 75mm lens, warm color science', 'text_to_image', 'curated', 4, true),
('Backlit portrait during magic hour, hair glowing with sunlight, soft natural shadows, peaceful expression, shot on Sony Venice 2, shallow depth of field, dreamy aesthetic', 'text_to_image', 'curated', 4, true),
('Sunset portrait on rooftop, city skyline background, golden light wrapping around subject, urban golden hour, shot on Arri Alexa 65, anamorphic lens, cinematic framing', 'text_to_image', 'curated', 4, true),
('Golden hour portrait in forest clearing, dappled sunlight through trees, natural setting, serene mood, shot on RED Raptor, 50mm lens, organic warm tones', 'text_to_image', 'curated', 4, true),
('Beach sunset portrait, wet hair and skin catching golden light, ocean spray in background, natural beauty, shot on Panavision DXL2, 85mm lens, warm color palette', 'text_to_image', 'curated', 4, true),
('Portrait during last light of day, subject in profile with golden glow, contemplative atmosphere, shot on Sony Venice, anamorphic format, rich warm highlights', 'text_to_image', 'curated', 4, true),
('Golden hour mountain portrait, subject on ridge with sun behind, epic landscape, adventurous spirit, shot on RED Monstro, wide lens, dramatic lighting', 'text_to_image', 'curated', 4, true),
('Sunset portrait in flower field, poppies catching golden light, subject in flowing dress, dreamy atmosphere, shot on Arri Alexa Mini, 85mm lens, soft focus', 'text_to_image', 'curated', 4, true),
('Golden hour portrait with lens flare, sun star visible, authentic moment, natural environment, shot on Panavision Millennium, anamorphic, warm organic feel', 'text_to_image', 'curated', 4, true),
('Backlit sunset portrait on pier, water reflecting golden light, peaceful mood, shot on Sony Venice 2, 135mm lens, compressed perspective', 'text_to_image', 'curated', 4, true),
('Portrait during magic hour in vineyard, grape vines framing subject, warm harvest light, shot on RED Komodo, 50mm lens, rich earth tones', 'text_to_image', 'curated', 4, true),

-- More High Fashion (15 prompts)
('Editorial beauty close-up, avant-garde makeup design, precise lighting highlighting features, shot on Phase One XF IQ4, macro lens, ultra high resolution', 'text_to_image', 'curated', 4, true),
('Vogue style portrait, haute couture fashion, impeccable styling, studio strobes creating dimension, shot on Hasselblad X2D, 90mm lens, editorial perfection', 'text_to_image', 'curated', 4, true),
('Fashion editorial portrait, designer clothing, architectural poses, clean white background, shot on Phase One, professional lighting setup, commercial quality', 'text_to_image', 'curated', 4, true),
('High fashion beauty shot, flawless skin, dramatic eye makeup, hair by top stylist, shot on Hasselblad H6D, ring light and strobes, magazine cover worthy', 'text_to_image', 'curated', 4, true),
('Editorial portrait with geometric makeup, bold fashion statement, modern styling, shot on Phase One XF, 80mm lens, artistic composition', 'text_to_image', 'curated', 4, true),
('Luxury fashion portrait, expensive jewelry and clothing, sophisticated lighting, shot on Hasselblad X2D, 120mm lens, high-end commercial', 'text_to_image', 'curated', 4, true),
('Beauty editorial close-up, natural glowing skin, subtle makeup perfection, soft studio lighting, shot on Phase One, macro detail, aspirational beauty', 'text_to_image', 'curated', 4, true),
('High fashion portrait with wind machine, dynamic hair movement, couture dress, dramatic lighting, shot on Hasselblad H6D, 90mm lens, editorial drama', 'text_to_image', 'curated', 4, true),
('Editorial beauty shot, dewy skin texture, fresh natural makeup, perfect retouching, shot on Phase One XF IQ4, 120mm lens, commercial beauty', 'text_to_image', 'curated', 4, true),
('Fashion portrait with colored gels, creative lighting design, avant-garde styling, shot on Hasselblad X2D, professional setup, artistic editorial', 'text_to_image', 'curated', 4, true),
('High fashion close-up, dramatic contouring, bold lip color, precision lighting, shot on Phase One, 150mm lens, beauty campaign quality', 'text_to_image', 'curated', 4, true),
('Editorial portrait in designer suit, corporate fashion, clean professional styling, shot on Hasselblad H6D, white background, commercial sophistication', 'text_to_image', 'curated', 4, true),
('Beauty editorial with wet hair look, glossy skin, modern styling, shot on Phase One XF, ring light setup, contemporary fashion', 'text_to_image', 'curated', 4, true),
('High fashion portrait with sculptural clothing, architectural design, dramatic shadows, shot on Hasselblad X2D, 90mm lens, artistic fashion', 'text_to_image', 'curated', 4, true),
('Editorial beauty shot with graphic eyeliner, bold makeup artistry, perfect skin, shot on Phase One, macro lens, beauty editorial excellence', 'text_to_image', 'curated', 4, true),

-- More Vintage Hollywood (15 prompts)
('Old Hollywood close-up, victory rolls hairstyle, red lips, butterfly lighting, shot on classic Panavision, black and white perfection', 'text_to_image', 'curated', 3, true),
('Vintage movie star portrait, fur stole and diamonds, sophisticated lighting, shot on old film stock simulation, golden age glamour', 'text_to_image', 'curated', 3, true),
('1940s Hollywood beauty, elegant styling, soft romantic lighting, shot on vintage lenses, classic cinema aesthetic', 'text_to_image', 'curated', 3, true),
('Glamour portrait in style of George Hurrell, dramatic shadows, star quality lighting, shot on classic portrait lens, Hollywood golden age', 'text_to_image', 'curated', 3, true),
('Classic movie star close-up, perfect 1950s makeup, soft focus glamour, shot on vintage cinema glass, timeless sophistication', 'text_to_image', 'curated', 3, true),
('Hollywood glamour with cigarette holder, elegant pose, dramatic lighting, shot on classic film stock simulation, vintage star power', 'text_to_image', 'curated', 3, true),
('Vintage beauty portrait, finger waves hairstyle, classic red lips, old Hollywood lighting, shot on Panavision vintage', 'text_to_image', 'curated', 3, true),
('1930s movie star portrait, art deco styling, sophisticated glamour, shot on period-appropriate glass, silver screen beauty', 'text_to_image', 'curated', 3, true),
('Classic Hollywood diva, dramatic eye makeup, fur and jewels, Hurrell-style lighting, shot on vintage lenses, star quality', 'text_to_image', 'curated', 3, true),
('Golden age glamour portrait, elegant gown, soft romantic lighting, shot on classic cinema lenses, timeless beauty', 'text_to_image', 'curated', 3, true),
('Vintage starlet close-up, perfect 1940s styling, dramatic butterfly lighting, shot on old film stock simulation', 'text_to_image', 'curated', 3, true),
('Hollywood glamour with pearls, sophisticated 1950s styling, classic portrait lighting, shot on vintage Panavision', 'text_to_image', 'curated', 3, true),
('Classic movie star beauty, platinum blonde hair, dramatic shadows, shot on vintage cinema glass, old Hollywood perfection', 'text_to_image', 'curated', 3, true),
('1940s glamour portrait, victory rolls and red lips, soft focus romance, shot on classic lenses, vintage sophistication', 'text_to_image', 'curated', 3, true),
('Vintage Hollywood close-up, perfect makeup and hair, star lighting setup, shot on period glass, golden age beauty', 'text_to_image', 'curated', 3, true),

-- More Modern Cinematic (15 prompts)
('Modern film portrait, natural lighting with drama, authentic emotion, shot on RED Komodo, anamorphic lens, indie cinema style', 'text_to_image', 'curated', 3, true),
('Contemporary cinematic close-up, window light with shadows, real moment captured, shot on Sony Venice, 85mm lens, modern realism', 'text_to_image', 'curated', 3, true),
('Dramatic modern portrait, urban setting, available light, shot on Arri Alexa Mini, 35mm lens, contemporary cinema feel', 'text_to_image', 'curated', 3, true),
('Cinematic character study, natural drama, subtle color grading, shot on RED Raptor, 50mm lens, modern indie aesthetic', 'text_to_image', 'curated', 3, true),
('Modern film portrait with depth, layered lighting, authentic performance, shot on Panavision DXL2, anamorphic, contemporary cinema', 'text_to_image', 'curated', 3, true),
('Contemporary dramatic close-up, window light creating mood, shot on Sony Venice 2, 75mm lens, modern filmmaking', 'text_to_image', 'curated', 3, true),
('Cinematic portrait in natural environment, available light drama, shot on Arri Alexa 65, wide lens, modern realism', 'text_to_image', 'curated', 3, true),
('Modern character portrait, subtle lighting, authentic emotion, shot on RED Monstro, 85mm lens, contemporary film style', 'text_to_image', 'curated', 3, true),
('Dramatic modern close-up, urban lighting, real moment, shot on Panavision Millennium, anamorphic, indie cinema aesthetic', 'text_to_image', 'curated', 3, true),
('Contemporary cinematic portrait, natural drama, shallow focus, shot on Sony Venice, 50mm lens, modern storytelling', 'text_to_image', 'curated', 3, true),
('Modern film character study, window light and shadows, shot on Arri Alexa Mini LF, 135mm lens, intimate cinema', 'text_to_image', 'curated', 3, true),
('Cinematic portrait with available light, urban setting, shot on RED Komodo, 35mm lens, contemporary realism', 'text_to_image', 'curated', 3, true),
('Modern dramatic portrait, layered natural lighting, shot on Panavision DXL2, 75mm lens, indie film aesthetic', 'text_to_image', 'curated', 3, true),
('Contemporary close-up, moody window light, authentic moment, shot on Sony Venice 2, anamorphic, modern cinema', 'text_to_image', 'curated', 3, true),
('Cinematic character portrait, natural environment, dramatic available light, shot on Arri Alexa 65, 50mm lens', 'text_to_image', 'curated', 3, true),

-- More Chiaroscuro (15 prompts)
('Dramatic side lighting portrait, deep shadows, highlight on face, classical painting style, shot on RED Monstro, 75mm lens, high contrast', 'text_to_image', 'curated', 2, true),
('Low key portrait with single light source, Caravaggio-inspired drama, rich blacks, shot on Panavision DXL2, 50mm lens, artistic chiaroscuro', 'text_to_image', 'curated', 2, true),
('Dramatic portrait with harsh shadows, single window light, Renaissance painting aesthetic, shot on Sony Venice, 85mm lens, classical lighting', 'text_to_image', 'curated', 2, true),
('Chiaroscuro close-up, directional lighting, sculptural shadows, shot on Arri Alexa Mini LF, 135mm lens, dramatic art style', 'text_to_image', 'curated', 2, true),
('Low key portrait, single source drama, deep shadow areas, shot on RED Raptor, 75mm lens, Rembrandt lighting', 'text_to_image', 'curated', 2, true),
('Dramatic side light portrait, rich contrast, painterly quality, shot on Panavision Millennium, 85mm lens, classical chiaroscuro', 'text_to_image', 'curated', 2, true),
('Chiaroscuro character study, single light sculpting features, shot on Sony Venice 2, 50mm lens, Renaissance inspired', 'text_to_image', 'curated', 2, true),
('Low key dramatic portrait, window light creating shadows, shot on Arri Alexa 65, anamorphic, artistic high contrast', 'text_to_image', 'curated', 2, true),
('Portrait with dramatic light fall-off, Caravaggio style, rich blacks and highlights, shot on RED Monstro, 85mm lens', 'text_to_image', 'curated', 2, true),
('Chiaroscuro close-up, single source creating dimension, shot on Panavision DXL2, 75mm lens, classical painting light', 'text_to_image', 'curated', 2, true),
('Dramatic low key portrait, side light emphasizing features, shot on Sony Venice, 135mm lens, Renaissance aesthetic', 'text_to_image', 'curated', 2, true),
('Single light portrait, dramatic shadow play, Rembrandt triangle, shot on Arri Alexa Mini, 85mm lens, painterly', 'text_to_image', 'curated', 2, true),
('Chiaroscuro drama, window light and shadows, classical composition, shot on RED Komodo, 50mm lens, artistic contrast', 'text_to_image', 'curated', 2, true),
('Low key character portrait, single source lighting, rich contrast, shot on Panavision Millennium, anamorphic', 'text_to_image', 'curated', 2, true),
('Dramatic side lighting close-up, deep shadows, shot on Sony Venice 2, 75mm lens, Caravaggio inspired', 'text_to_image', 'curated', 2, true),

-- Soft Natural Light (10 prompts)
('Portrait in soft daylight, north-facing window, even illumination, shot on Sony Venice, 50mm lens, natural and flattering', 'text_to_image', 'curated', 2, true),
('Gentle natural light portrait, sheer curtain diffusion, soft shadows, shot on RED Komodo, 75mm lens, organic feel', 'text_to_image', 'curated', 2, true),
('Soft window portrait, natural skin tones, subtle modeling, shot on Panavision DXL2, 85mm lens, gentle lighting', 'text_to_image', 'curated', 2, true),
('Natural light close-up, diffused daylight, soft features, shot on Arri Alexa Mini, 135mm lens, authentic beauty', 'text_to_image', 'curated', 2, true),
('Portrait with soft natural illumination, window light wrapping around subject, shot on Sony Venice 2, 50mm lens', 'text_to_image', 'curated', 2, true),
('Gentle daylight portrait, natural diffusion, flattering shadows, shot on RED Raptor, 85mm lens, organic lighting', 'text_to_image', 'curated', 2, true),
('Soft natural window light, authentic skin texture, gentle modeling, shot on Panavision Millennium, 75mm lens', 'text_to_image', 'curated', 2, true),
('Natural portrait with diffused light, soft and even, shot on Arri Alexa 65, 50mm lens, gentle aesthetic', 'text_to_image', 'curated', 2, true),
('Window light portrait, sheer diffusion, natural beauty, shot on Sony Venice, anamorphic, soft flattering light', 'text_to_image', 'curated', 2, true),
('Soft natural close-up, gentle window illumination, authentic features, shot on RED Monstro, 85mm lens', 'text_to_image', 'curated', 2, true)
ON CONFLICT DO NOTHING;